### ISSUE TITLE
If securebootmodel is set OC won't load 

### ISSUE THREAD

**Issue by finner** [johnnync13/Xiaomi-Notebook-Air-1Gen#101]
Trying to experiment with the new airportitwlm.kext that provides native WiFi selection however it requires securebootmodel set to Default. Unfortunately after setting this option with open core configurator upon reboot open core OS selection won't pop up, it is stuck in MI logo.

**Comment by shomerchang** [comment]
bios?  Airportitwlm.kext doesn't need to set secureboot, my gaming laptop works well.

**Comment by finner** [comment]
Bios A09. How did you install it?

**Comment by shomerchang** [comment]
> Bios A09. How did you install it?

sorry, my fault. you said OC's setting.
but on my laptop(air)  " securebootmodel set to Default " still works well
![截屏2020-09-21 17 57 16](https://user-images.githubusercontent.com/17776090/93754241-032cfb80-fc34-11ea-97ce-b6ea8ca21f4e.png)
![截屏2020-09-21 17 57 40](https://user-images.githubusercontent.com/17776090/93754252-06c08280-fc34-11ea-95a7-543bd1338256.png)

**Comment by abmfy** [comment]
If you want to have a try on AirPortItlwm, set "SecureBootModel" to "Default" and "DmgLoading" to "Signed". That just works.

**Comment by finner** [comment]
> If you want to have a try on AirPortItlwm, set "SecureBootModel" to "Default" and "DmgLoading" to "Signed". That just works.

I tried that but after choosing OSX on the boot screen the screen becomes black for a few seconds and then it takes me back to the OS selection window. Everything is working fine though until 7.4.2 EFI.

**Comment by finner** [comment]
After updating to 10.15.17 everything works fine even with the latest EFI and airpprtitwlm
