### ISSUE TITLE
7.4.3 not boot OC

### ISSUE THREAD

**Issue by rodion1322** [johnnync13/Xiaomi-Notebook-Air-1Gen#102]
New version not boot, just black screen. On OC boot step.
Thanks for your work!

**Comment by pc439527** [comment]
same mistake on big sur beta8

**Comment by Nxys** [comment]
same mistake on catalina 10.15.7

**Comment by abmfy** [comment]
Same om Big Sur Beta 9 and you can fix that by setting "SecureBootModel" back to "Disabled".

**Comment by abmfy** [comment]
If you want to have a try on AirPortItlwm, set "SecureBootModel" to "Default" and "DmgLoading" to "Signed". That just works.

**Comment by jimmymitlavigne** [comment]
> If you want to have a try on AirPortItlwm, set "SecureBootModel" to "Default" and "DmgLoading" to "Signed". That just works.

I set this two key. and it boot now(7.4.3), but seems this windows key and alt key has switched. If I want to copy something, I have to press alt+c, how to change it back.

**Comment by abmfy** [comment]
Reset modifier key settings in Preference -> Keyboard

**Comment by abmfy** [comment]
This is for trying to be more like a true Mac since on a Mac the command key is next to the space bar. If you like using Ctrl+C to copy, set the behavior of Control to Command.
In default settings of this version of EFI, Ctrl and Fn doesn't change their behavior and Windows key is mapped to Option, Alt to Command

**Comment by jimmymitlavigne** [comment]
> This is for trying to be more like a true Mac since on a Mac the command key is next to the space bar. If you like using Ctrl+C to copy, set the behavior of Control to Command.
> In default settings of this version of EFI, Ctrl and Fn doesn't change their behavior and Windows key is mapped to Option, Alt to Command

The problem is solved. Thank you!
