### ISSUE TITLE
What version of intel Wi-Fi that you guys using now?

### ISSUE THREAD

**Issue by jimmymitlavigne** [johnnync13/Xiaomi-Notebook-Air-1Gen#103]
## What version of intel Wi-Fi that you guys using now?

I am currently using a version downloaded from the forum, using NVRAM to connect to Wi-Fi, it can automatically connect to the specified Wi-Fi at boot, and use the command line to switch Wi-Fi

### The disadvantage is that it often disconnects, although it will reconnect immediately, but it still affects the use experience a bit

I saw they discussing this OpenIntelWireless/HeliPort, how is the experience of using this? Is it stable? Thank you in advance.

**Comment by abmfy** [comment]
AirPortItlwm
https://github.com/OpenIntelWireless/itlwm

**Comment by jimmymitlavigne** [comment]
> AirPortItlwm
> https://github.com/OpenIntelWireless/itlwm

THanks for your reply. So how to use this?  drop the kext to efi folder?

**Comment by abmfy** [comment]
> > AirPortItlwm
> > https://github.com/OpenIntelWireless/itlwm
> 
> THanks for your reply. So how to use this? drop the kext to efi folder?

Use the latest version of EFI folder, set “DMGLoading“ to “Signed” in config.plist, drag it to EFI/Kexts then add it in config.plist

**Comment by abmfy** [comment]
Or if needed I could provide my EFI folder

**Comment by jimmymitlavigne** [comment]
> Or if needed I could provide my EFI folder

I get the itlwm working now, But I don’t know if I am operating correctly, on the top menu it have two wifi icon...
If you can provide me with your plist file for reference, it would be very helpful. Thanks!

**Comment by abmfy** [comment]
Maybe you didn't disable your former itlwm

[config.plist.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/5339410/config.plist.zip)

**Comment by jimmymitlavigne** [comment]
> Maybe you didn't disable your former itlwm
> 
> [config.plist.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/5339410/config.plist.zip)

THANKS i will try to disable it
