### ISSUE TITLE
Not working with the latest versions of Catalina

### ISSUE THREAD

**Issue by UnknownH** [johnnync13/Xiaomi-Notebook-Air-1Gen#105]
I've followed the steps on a clean Windows installation and regardless of how I try I won't be able to make it work for Catalina 10.15.6 or 10.15.7. I'd say that the image creation ends too fast, but in any case the readme steps won't produce a successful installation on Xiaomi 1st gen. But I've also tried creating the image myself with BDUtility (which works for 10.15.3) and replacing the EFI folder but that won't work either

**Comment by johnnync13** [comment]
try the new release
