### ISSUE TITLE
latest releases won't install.

### ISSUE THREAD

**Issue by houzhibin** [johnnync13/Xiaomi-Notebook-Air-1Gen#106]
I have the 1gen model of mi air 13 with i5 6200u. BIOS version A09. I've tried the OC methods with 7.4.4, 7.4.3 and 7.4.1 release packages but none of them worked. With 7.4.3 it just doesn't see the bootloader icon. With 7.4.1 I can see the Install Catalina icon but after clicking it, it halted. I've googled some sites and think there might be something wrong with config.plist settings. Looking forward to some fixes. Thanks a lot for your amazing work!

**Comment by sakoula** [comment]
@houzhibin check https://github.com/sakoula/XiaoMi-Air-6200U

**Comment by johnnync13** [comment]
@houzhibin I update the efi
