### ISSUE TITLE
7.4.6 "OC: Failed to load configuration"

### ISSUE THREAD

**Issue by rodion1322** [johnnync13/Xiaomi-Notebook-Air-1Gen#107]
This version just get error "OC: Failed to load configuration"

**Comment by johnnync13** [comment]
try the last release  @rodion1322

**Comment by rodion1322** [comment]
again same problem in 7.4.7 and 7.4.8 versions

**Comment by johnnync13** [comment]
v7.4.8 is working... try clean installation
