### ISSUE TITLE
Can't sleep on Big Sur

### ISSUE THREAD

**Issue by rijianyunxi** [johnnync13/Xiaomi-Notebook-Air-1Gen#109]
Can't sleep on Big Sur,Power off without power off,the Intel network card works normally,and airportitwm cannot be used on 10.15.6

**Comment by Wenfeng12138** [comment]
我也遇到了不能正常关机的问题，但是要在Big Sur里用airportitlwn需要在OCC里把SecureBootMode设为Disable

**Comment by kulanchong** [comment]
小米air13，i7 6500u ,更换bcm94360cs网卡，oc引导，bigsur11，盒盖睡眠就唤不醒类似死机，关机后不断电 电源指示灯常亮，求救

**Comment by 351286781** [comment]
The same issues,sleep work on 10.15.7 and Big Sur 11.0Beta but 11.0.1 (20B50) not.

**Comment by shomerchang** [comment]
> 我也遇到了不能正常关机的问题，但是要在Big Sur里用airportitlwn需要在OCC里把SecureBootMode设为Disable

我也是这样的，每次都是关机之后再强制关

**Comment by itq5** [comment]
关机异常，大家有找到解决方法吗？

**Comment by jimmymitlavigne** [comment]
> > 我也遇到了不能正常关机的问题，但是要在Big Sur里用airportitlwn需要在OCC里把SecureBootMode设为Disable
> 
> 我也是这样的，每次都是关机之后再强制关

请问你们找到解决办法了吗   我也是每次都强制关机

**Comment by johnnync13** [comment]
it's usb problems...
