### ISSUE TITLE
is the link right?主頁的鏈接正確嗎？

### ISSUE THREAD

**Issue by aaron2wh** [johnnync13/Xiaomi-Notebook-Air-1Gen#112]
在項目主頁的說明中，有在製作EFI步驟如下描述：
---------------------------------
Making the USB stick Xiaomi compatible:

Download the latest version of the EFI folder from [here](https://github.com/johnnync13/Xiaomi-Mi-Air/releases)
Extract it somewhere
-----------------------------
但是鏈接指向的是另外一個項目小米二代air的EFI下載處。
所以請問這裡是否作者把自己的兩個項目鏈接搞混了？

**Comment by shomerchang** [comment]
you can view [https://blog.daliansky.net](https://blog.daliansky.net)/, maybe it can help you.
------------------------------------------------------------------------------------------------------------------------------
你可以看看黑果小兵的，里面步骤很详细，只用这里的EFI，其他的东西看小兵的就可以了(像制作镜像什么的)。
