### ISSUE TITLE
一代米本，也就是六代i5不带指纹的版本休眠后无法唤醒

### ISSUE THREAD

**Issue by dumet12138** [johnnync13/Xiaomi-Notebook-Air-1Gen#114]
系统最新11.2.2.
bios已禁用cfg lock
休眠后任何按键包括电源键都没有反应，电源灯亮，只能强行关机
貌似关机也有问题，正常关机好像并不会断电，因为关机后按电源键没有反应，长按电源才能正常开机
不知道什么情况

**Comment by dumet12138** [comment]
OC配置里面的cfglock两项全部NO也试过，一样的结果

**Comment by shomerchang** [comment]
是有这个问题，不知道怎么解决

**Comment by jiangfeiyu** [comment]
同样问题，一直在等更新

**Comment by pc439527** [comment]
估计作者都放弃更新了 好几个月了

**Comment by edik-debug** [comment]
到现在也没解决
