### ISSUE TITLE
Some issues with the latest version

### ISSUE THREAD

**Issue by Nxys** [johnnync13/Xiaomi-Notebook-Air-1Gen#12]
1. Touchpad is not working;
2. Shutdown is not working;
3. Hibernate can't wake up.

**Comment by johnnync13** [comment]
trackpad is working now like magic trackpad

**Comment by bianyingshan** [comment]
Has the shutdown problem been solved? I have given all the ports of hacktool testing on my side before.


I debug all my USB ports one by one with software as follows:
USB1：
2.0：HS04
USB2：
3.0：SS01
2.0：HS01

HUB dock of official TypeC：HS03 SS03

Through debugging, I found the following phenomena:
Different contents within the USBPort. kext file can lead to the following phenomena

AppleUSBXHCIPCI
IOProviderMergeProperties

port-count

BQAAAA==
data is “BQAAAA==”：Can shut down, port abnormal

data is “DwAAAA==”：All ports are normal and cannot shut down


USBPort. kext is also attempted to be generated and replaced according to the injection results, but it has not been effectively solved.

**Comment by johnnync13** [comment]
@bianyingshan @Nxys trackpad now is working like magic trackpad

**Comment by johnnync13** [comment]
@bianyingshan this laptop has usb 3.0? And how many?

**Comment by finner** [comment]
Shutdown doesn't work with 3.6.. Didn't try the USB ports how they operate.. They left works fine with the USB wifi dongle.
Both ports are USB3

**Comment by johnnync13** [comment]
@finner use 3.7 not 3.6

**Comment by JaylanWood** [comment]
HS01---USB2---0x01---Tested by myself.USB port No.1 in the right of mibook.
SS01---USB3---0x0D---Tested by myself.USB port No.1 in the right of mibook.
HS04---USB2---0x04---Tested by myself.USB port No.2 in the left of mibook.
SS04---USB3---0x10---Tested by myself.USB port No.2 in the left of mibook.

HS05---USB2---0x05---XiaoMi USB 2.0 Webcam
HS07---USB3---0x07---IOUSBHostDevice

Xiaomi Notebook Air 13(i5-6200U) has 2 USB3 ports,1 HDMI port,1 Type-C port with charging.
I tested the 2 USB3 ports,they are HS01\SS01 and HS04\SS04,but I don't have any Type-C device.
I am not sure if HS07 is the Type-C port.

I tried V3.6
It just can not shutdown with power cut off,the power LED just lighting.

I just tried V3.7
Still,Shutdown is not working,maybe HS07 is the Type-C and HS03 is not needed.

**Comment by SilenceLiew** [comment]
HS07 is Bluetooth hs03 andss03 is type-c

**Comment by johnnync13** [comment]
try v3.8

**Comment by JaylanWood** [comment]
I tried V3.8
Shutdown is not working.

I tried the USB ports in Hackintool.

XHC1 ▸ XHC
EHC1 ▸ EH01
EHC2 ▸ EH02
put USBInjectAll.kext in EFI/CLOVER/kexts/Other
reboot
tied the USB ports in Hackintool.

HS01---USB2---0x01---USB port No.1 in the right of mibook.
SS01---USB3---0x0D---USB port No.1 in the right of mibook.
HS04---USB2---0x04---USB port No.2 in the left of mibook.
SS04---USB3---0x10---USB port No.2 in the left of mibook.

HS05---USB2---0x05---XiaoMi USB 2.0 Webcam
HS07---USB3---0x07---IOUSBHostDevice(Maybe the bluetooth)

I order a Type-C device and it should be received in tomorrow.
I will try it once.

**Comment by JaylanWood** [comment]
Here is an EFI for OSX 10.12.3
I tried it and it is working perfectly in 10.12.3.No shutdown problem.
But it has the same shutdown problem since 10.12.6.

This EFI is from insanelymac.com.
https://www.insanelymac.com/forum/topic/319656-guide-xiaomi-mi-notebook-air-13/

I upload it to my google drive.
https://drive.google.com/file/d/1pi0Q-7nt9N0q4dwSrIskhy2D7i2VUiIh/view?usp=sharing

**Comment by JaylanWood** [comment]
I tested every USB ports in Hackintosh.
HS01---USB2---0x01---USB port No.1 in the right of mibook.
SS01---USB3---0x0D---USB port No.1 in the right of mibook.
HS04---USB2---0x04---USB port No.2 in the left of mibook.
SS04---USB3---0x10---USB port No.2 in the left of mibook.
HS03---Type-c+sw----The only Type-c port in the right of mibook.
SS03---Type-c+sw----The only Type-c port in the right of mibook.

HS05---USB2---0x05---XiaoMi USB 2.0 Webcam
HS07---USB3---0x07---IOUSBHostDevice(Maybe the bluetooth)

I tried to fix the USB like this:
HS01---USB2
HS03---Type-c+sw
HS04---USB2
HS05---internal
HS07---internal
SS01---USB3
SS03---Type-c+sw
SS04---USB3

Still,Shutdown is not working.

When shutdown:
Screen off.
The LED in power button keep lighting.
keyboard backlight off no matter click it or not.
Insert USB disk and the USB disk LED will keep lighting.

**Comment by SilenceLiew** [comment]
only use usb2.0 (delete ss01,ss03 ss04)could shutdown. I don't know why

**Comment by JaylanWood** [comment]
Agree with SilenceLiew.
Deleting SS01,SS03,SS04 can fix shutdown.
So strange

**Comment by JaylanWood** [comment]
Agree with SilenceLiew.
Deleting SS01,SS03,SS04 can fix shutdown.But no more USB3
So strange

**Comment by johnnync13** [comment]
send me usbports.kext with all usb inject correctly @JaylanWood

**Comment by JaylanWood** [comment]
USBPorts.kext

Only USB2(fix shutdown+No USB3)：
https://drive.google.com/file/d/15esjm4mjob8KptqQFQr57hVOOhzWTkBT/view?usp=sharing

USB3+USB2(Can't shutdown)：
https://drive.google.com/file/d/1WlhNgjHkq59UpbF6z0oRmhnflUcoFtuk/view?usp=sharing

**Comment by FallenChromium** [comment]
Report: Still doesn't shutdown as of 4.1

**Comment by johnnync13** [comment]
I try to fix dsdt.aml to shutdown on next days

**Comment by johnnync13** [comment]
https://github.com/jackxuechen/fixusb

**Comment by SilenceLiew** [comment]
can't shutdown yet

**Comment by SilenceLiew** [comment]
still can't shutdown

**Comment by johnnync13** [comment]
@SilenceLiew I know. I do not think I can get to a problem, since I do not have this laptop

**Comment by johnnync13** [comment]
@JaylanWood send me the three files. UIAC, USBX and kext please

**Comment by JaylanWood** [comment]
> @JaylanWood send me the three files. UIAC, USBX and kext please

I tried to fix USB with you EFI by using Hackintool and USBInjectAll 0.7.1,but there is a problem
Like this:
XHC1 ▸ XHC
EHC1 ▸ EH01
EHC2 ▸ EH02
Remove USBports.kext
Put USBInjectAll.kext in EFI/CLOVER/kexts/Other
Reboot
**Ban logo appears**
**Can't boot**

<hr>

I do the same thing with a EFI from https://blog.daliansky.net/

It can shutdown when USBports.kext only USB 2.0
https://drive.google.com/open?id=1vwe-4TttqLishFyFz6q1sK28aM-9nVaC

It can't shutdown when USBports.kext with USB 2.0+USB 3.0
https://drive.google.com/file/d/1vwe-4TttqLishFyFz6q1sK28aM-9nVaC/view?usp=sharing

When fixing USB with Hackintool
Just USBPorts.kext and SSDT-UIAC.aml
No SSDT-USBX.aml

Here is the files:
Only USB2(fix shutdown+No USB3)：
https://drive.google.com/file/d/15esjm4mjob8KptqQFQr57hVOOhzWTkBT/view?usp=sharing
USB3+USB2(Can't shutdown)：
https://drive.google.com/file/d/1WlhNgjHkq59UpbF6z0oRmhnflUcoFtuk/view?usp=sharing

**Comment by johnnync13** [comment]
@JaylanWood take a photo on usb fix hackintool with anything fixes

**Comment by JaylanWood** [comment]
![Hackintool](https://user-images.githubusercontent.com/49611610/61013278-a50c5380-a3b4-11e9-9529-189de32d21d3.jpg)

**Comment by johnnync13** [comment]
Is this with all connections usb 2.0, 3.0 and type-C?. I Think that one SS0X is the problem. You should remove One by One and look which of them creates the conflict and write me with your feedback

**Comment by JaylanWood** [comment]
Shutdown don't works only with usbinjectall and SSDT-EC.aml
I am trying the SS0X ports.

**Comment by whtiehack** [comment]
[This version](https://github.com/whtiehack/XiaoMi-Air) works fine on OS X10.13.5 and has some bugs on other versions. 
We can refer to it.
I hope to support the high version of OS X.Thanks @johnnync13

**Comment by JaylanWood** [comment]
![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
ss03 and ss04 cause shutdown problem

**Comment by SilenceLiew** [comment]
> ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> ss03 and ss04 cause shutdown problem

I tried only delete ss04  could shutdown

**Comment by JaylanWood** [comment]
![Xiaomi Notebook air 13 Gen1 2016](https://user-images.githubusercontent.com/49611610/61035946-ae201380-a3fa-11e9-8099-17c5c1f82f07.jpg)
<br>
![Bios](https://user-images.githubusercontent.com/49611610/61035969-b710e500-a3fa-11e9-9961-9226bee68f79.jpg)
BIOS A5

**Comment by JaylanWood** [comment]
![Fix USB based on daliansky EFI](https://user-images.githubusercontent.com/49611610/61036402-a0b75900-a3fb-11e9-8b17-26bac3716c07.jpg)

Fix USB based on daliansky EFI
SS03 and SS04 cause the shutdown problem
<hr>
![Fix USB based on johnnync13 V4 7](https://user-images.githubusercontent.com/49611610/61036441-b4fb5600-a3fb-11e9-91eb-8b6b16cefe9b.jpg)

Fix USB based on johnnync13 V4.7
SS03 cause the shutdown problem.
No SS04 in USBInjectAll.kext

USBPorts.kext+SSDT-UIAC.aml+SSDT-USBX.aml:
[USB2+Cam+Bluetooth+SS01+SS03=can not shutdown.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/3381105/USB2%2BCam%2BBluetooth%2BSS01%2BSS03.can.not.shutdown.zip)

[USB2+Cam+Bluetooth+SS01=fix shutdown.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/3381106/USB2%2BCam%2BBluetooth%2BSS01.fix.shutdown.zip)

[USB2+Cam+Bluetooth=fix shutdown.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/3381108/USB2%2BCam%2BBluetooth.fix.shutdown.zip)

**Comment by JaylanWood** [comment]
> > ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> > ss03 and ss04 cause shutdown problem
> 
> I tried only delete ss04 could shutdown

What is your Bios Version？

**Comment by SilenceLiew** [comment]
> > > ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> > > ss03 and ss04 cause shutdown problem
> > 
> > 
> > I tried only delete ss04 could shutdown
> 
> What is your Bios Version？

A06

**Comment by JaylanWood** [comment]
> > > > ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> > > > ss03 and ss04 cause shutdown problem
> > > 
> > > 
> > > I tried only delete ss04 could shutdown
> > 
> > 
> > What is your Bios Version？
> 
> A06
Mine is A05

Maybe **Bios Version** is the reason.

Could you try to fix USB with daliansky EFI and  johnnync13 EFI V4.7,write down the result,please?

**Comment by SilenceLiew** [comment]
> > > ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> > > ss03 and ss04 cause shutdown problem
> > 
> > 
> > I tried only delete ss04 could shutdown
> 
> What is your Bios Version？

And there has a A09 edition.    http://bbs.xiaomi.cn/t-37742666  
in pcbeta there has someone could shutdown ,I asked his bois version and wait for his reply

**Comment by JaylanWood** [comment]
> > > > ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> > > > ss03 and ss04 cause shutdown problem
> > > 
> > > 
> > > I tried only delete ss04 could shutdown
> > 
> > 
> > What is your Bios Version？
> 
> And there has a A09 edition. http://bbs.xiaomi.cn/t-37742666
> in pcbeta there has someone could shutdown ,I asked his bois version and wait for his reply

我问了小米官网在线客服，要去线下维修店升级BIOS，或者打电话问问能不能把文件发过来。现在店铺都下班了，以后再试。

**Comment by FallenChromium** [comment]
@SilenceLiew I have the upgrade file but I wasn't able to update as it's an .exe file. Porting .bin to EFI version of Insyde's flasher caused freeze, luckily my laptop wasn't bricked. If you have Windows installed I can upload a file here.

**Comment by johnnync13** [comment]
use the last version ever.
http://bbs.xiaomi.cn/t-37742666

**Comment by johnnync13** [comment]
If you delete ss03 but not  SS04. Can you shutdown?

**Comment by johnnync13** [comment]
> > > > ![ALL](https://user-images.githubusercontent.com/49611610/61023835-13b1d700-a3de-11e9-97a3-daa10002d5f7.jpg)
> > > > ss03 and ss04 cause shutdown problem
> > > 
> > > 
> > > I tried only delete ss04 could shutdown
> > 
> > 
> > What is your Bios Version？
> 
> And there has a A09 edition. http://bbs.xiaomi.cn/t-37742666
> in pcbeta there has someone could shutdown ,I asked his bois version and wait for his reply


tell him to give you his EFI too

**Comment by JaylanWood** [comment]
EFI V4.7+Bios A05+delete ss03 but not SS04=can not shutdown

EFI V4.7+Bios A05+ALL as 3.0=can not shutdown

**Comment by johnnync13** [comment]
this is my configuration for Xiaomi 12.5 skylake m3-6y30. I think that 
there's something wrong that's why it does not shutdown, because on my laptop the same thing happened
<img width="1440" alt="Captura de pantalla 2019-07-11 a las 17 59 35" src="https://user-images.githubusercontent.com/22727137/61066592-1de7cb80-a406-11e9-9e9a-9000f821c3e6.png">

**Comment by JaylanWood** [comment]
I see
It is so strange that HS02 as USB3,SS03 as USB3 not Type-C
It seem to be a special case as Xiaomi's Laptop.
I should try USB one by one.Try each one type as USB2\USB3\TypeC and test if it can be shutdown.

**Comment by johnnync13** [comment]
Because if usb 3.0 connect usb 2.0 device, HS02 is activated but the port is usb 3.0

**Comment by JaylanWood** [comment]
Bios A05
Leave only SS03 as USB2/USB3/Type-C/Type-C+SW/Internal , remove other ports , can not shutdown.
Leave only SS04 as USB2/USB3/Type-C/Type-C+SW/Internal , remove other ports , can not shutdown.
<hr>
In my case , BIOS A05 ,
SS03 and SS04 both case the shudown problem no mater what ports type I select in Hackintool.
In SilenceLiew's case , BIOS A06 , only SS04 case the shudown problem.
I am not going to up upgrade BIOS for now since this laptop is my main working PC.

But it is acceptable since I never use the Type-C(HS03) and I always put a usb wifi in HS04.
It is not perfect,but it is good enough for me.
Thanks,johnnync

**Comment by johnnync13** [comment]
I recommend updating the BIOS.  It is not dangerous and there are always improvements.  A09 heats the equipment less.

**Comment by Tomas1861** [comment]
@JaylanWood ， Did those USB ports work well when your laptop wakes up after sleep for a while?

**Comment by ggggiaqgyd** [comment]
This EFI consumes electricity a little fast。
_https://github.com/whtiehack/XiaoMi-Air_ this power better。
but other is not well

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/v5.1
use this!
If you have problem with performance, use this https://github.com/stevezhengshiqi/one-key-cpufriend and copy kexts to clover-> kexts->others

**Comment by johnnync13** [comment]
Now, if you look carefully at the IOUSBHostFamily Info.plist, you find that newer SMBIOS are missing. Such as MacBookPro9,1, iMac17,1, and MacBookPro13,x. These models must use a different method for USB power property injection.

https://www.tonymacx86.com/threads/guide-usb-power-property-injection-for-sierra-and-later.222266/

I think the problem could be here, in the option to choose what type of SMBIOS

**Comment by johnnync13** [comment]
Can everyone send me  config.plist with this options?
<img width="1440" alt="Screenshot 2019-09-24 at 17 44 18" src="https://user-images.githubusercontent.com/22727137/65527650-48b8ca80-def3-11e9-96f6-b47839f68c46.png">
<img width="1440" alt="Screenshot 2019-09-24 at 17 46 13" src="https://user-images.githubusercontent.com/22727137/65527651-48b8ca80-def3-11e9-8a67-99197d837833.png">
<img width="1440" alt="Screenshot 2019-09-24 at 17 46 16" src="https://user-images.githubusercontent.com/22727137/65527652-48b8ca80-def3-11e9-974a-54384601924d.png">

**Comment by bossoq** [comment]
1.To fix MSR 0xE2 (CFG Lock) // No need for clover KernelPM/AICPUPM/KernelHotpatches
`setup_var 0x84A 0x00`
2.To fix DVMT pre-alloc (Change DVMT to 96 or 128M) // No need for Whatevergreen FB stolen men patch
`setup_var 0x180 0x03` or `setup_var 0x180 0x04`
This patch verified on BIOS A06 and A09.

For anyone who want to try to completely disable 940MX and Intel WiFi (This also disable 940MX and WiFi in Windows since it disable at UEFI level)
1.Disable PCIE Root Port 1
`setup_var 0x116 0x00`
2.Disable PCIE Root Port 5
`setup_var 0x11A 0x00`
After patch these 2 variables, there is no RP01 and RP05 show in Hackintool or IOReg.

For HDMI audio fix => You need to add framebuffer-con2-enable and framebuffer-con2-type to device properties. This will change connector-type from DP to HDMI.
Note: You will also need to patch fb-stolen-mem if you did not use setup_var method to change DVMT pre-alloc to greater than 64M.
```
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
<dict>
	<key>AAPL,ig-platform-id</key>
	<data>
	AAAbGQ==
	</data>
	<key>AAPL,slot-name</key>
	<string>Internal@0,2,0</string>
	<key>device_type</key>
	<string>VGA compatible controller</string>
	<key>disable-external-gpu</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con2-enable</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con2-type</key>
	<data>
	AAgAAA==
	</data>
	<key>hda-gfx</key>
	<string>onboard-1</string>
	<key>model</key>
	<string>Skylake GT2 [HD Graphics 520]</string>
</dict>
```

**Comment by bossoq** [comment]
For USB issue, I still cannot find any way to fix this.

HS01//SS01 => USB3 => Right Port => Type 3
HS03//SS03 => USB-C + SW => Right USB-C Port => Type 9
HS04//SS04 => USB3 => Left Port => Type 3
HS05 => Internal Webcam => Type 255 // Not tested since I broke my ribbon cable already. It rarely works in Windows.
HS07 => Internal Bluetooth (via soldered M.2 Intel WiFi) => Type 255 (For me, I disabled this port since bluetooth is not working in macOS anyway, except VM firmware injection method)

Interestingly, I found SS02 in DSDT which I think it's connected to M.2 B Key (WWAN Slot). I plan to use this port for Bluetooth on BCM94360.

For my Scenario (Xiaomi Air 13.3 i7-6500U with A09)
1. Disable SS03 and SS04
- First Sleep via menu => worked
- First Sleep via clamshell close => worked but USB not functioned after wakeup. We should try to debug on _PRW // _GPE // LID0 // other EC call methods.
- Second Sleep (no reboot) both menu and clamshell result in sleep failure. Screen turned black, Power LED stayed on, USB Power cutoff, No keyboard lighted, Fans spin.
- Shutdown => worked // Laptop completely shutdown. No power led.
2. Enable any SS03 or SS04 results in sleep, shutdown not working.
`pmset -g log` show Sleep Failure with some random code.

I think for i5 model with A09, disable only SS04 solve the problem. However, i7 model (with A06 or A09) needs to disable both SS03 and SS04 which partially solve the problem. This is weird since both i5 and i7 models use same BIOS and I don't think XiaoMi change PCB design for both 2 models.

**Comment by bossoq** [comment]
I also found some error in SSDT-KBD0 for brightness key. You need to tap `_SB.PCI0.LPCB.EC0` instead of `_SB.PCI0.LPCB.EC` and External Reference to `_SB_.PCI0.LPCB.EC0_` instead of `_SB_.PCI0.LPCB.EC__`.

```
DefinitionBlock ("", "SSDT", 2, "Xiaomi", "_KBD", 0x00000000)
{
    External (_SB_.PCI0.LPCB, DeviceObj)    // (from opcode)
    External (_SB_.PCI0.LPCB.EC0_, DeviceObj)    // (from opcode)
    External (_SB_.PCI0.LPCB.KBD0, DeviceObj)    // (from opcode)

    Scope (_SB.PCI0.LPCB.EC0)
    {
        Method (_Q1C, 0, NotSerialized)  // _Qxx: EC Query
        {
            Notify (\_SB.PCI0.LPCB.KBD0, 0x0406)
        }

        Method (_Q1D, 0, NotSerialized)  // _Qxx: EC Query
        {
            Notify (\_SB.PCI0.LPCB.KBD0, 0x0405)
        }
    }
}
```

**Comment by dawg115** [comment]
@bossoq I only disabled SS04 (i7 a06) and it fixed my shutdown

**Comment by johnnync13** [comment]
@bossoq @dawg115 if you can help and create pull request to change my code on GitHub, I will thank you. I had the Xiaomi mi Air 2018 but I sold it because it is important for me to take thunderbolt 3 to program with an external graphic such as TensorFlow or Cuda Cores

**Comment by bossoq** [comment]
@johnnync13 4 changes commit. 2 of them are SSDT-KBD0 brightness fix for Clover and OC. Another 2 are CPUFriend generate for i7-6500U model.

**Comment by dawg115** [comment]
can someone tell what are SS03 and SS04? I disabled them and I can shutdown now

**Comment by bossoq** [comment]
@dawg115 SS03 is USB3 connection on Right Type C port.
SS04 is USB3 connection on Left USB-A port.
Disable them makes your laptop to not able to connect USB3 device to those ports. They are still able to connect USB2 devices eg. mouse, keyboard or partially plugged USB3 device (Not fully plugged, so the SuperSpeed pins are not contacted // This is not possible for USB-C port.).

**Comment by johnnync13** [comment]
@bossoq thanks a lot

**Comment by johnnync13** [comment]
nobody has the bios a09.zip?

**Comment by bossoq** [comment]
@johnnyc13 I do have. You need bios dump or original flash file?

**Comment by johnnync13** [comment]
The original flash, .exe to upload to repository

**Comment by bossoq** [comment]
@johnnync13  Uploaded

**Comment by johnnync13** [comment]
https://github.com/hackintosh-stuff/Fix-usb-sleep

**Comment by johnnync13** [comment]
https://github.com/osy86/USBWakeFixup

**Comment by PeterWintner** [comment]
efi v5.2，when i close lid until sleep, then open lid, it can be awake, but USB ports not work anymore. But if I click sleep button from the menu bar redo clsose and open lid , everything is ok. What should I do?

**Comment by xuyoji** [comment]
same problem ⬆️

**Comment by xuyoji** [comment]
@johnnync13 @bossoq @dawg115 
I just find my HDMI port is not working. However, it works on type-c hub's HDMI port. I tried to  fix it by change the patch on the display port by Hackintool, but failed. How about your HDMI port? Do your have any idea? Thanks a lot.

**Comment by FallenChromium** [comment]
I have created a version of BIOS update which uses UEFI Shell, so ones who don't have windows could update too. It didn't solve my problem though, I have a 1st-gen Air with i5-6200 and it doesn't sleep nor shut down, even with SS03 and SS04 disabled, even with all USB2.0 files up this thread. Can somebody help me with this? It's really annoying. Also I would love to disable HS07 but even if I delete it from SSDT and injectors, it still appears, conflicting with my BT dongle. I've tried latest 5.3 OpenCore. Help will be really appreciated :) Here's the zip, to update bios you should unarchive it to FAT32 usb flash drive and boot it from F12 menu: (google drive)[https://drive.google.com/file/d/1ZIdW7u5lxNpa0JA-6LJzuEien3uV3yWH/view?usp=sharing]

**Comment by xuyoji** [comment]
> I have created a version of BIOS update which uses UEFI Shell, so ones who don't have windows could update too. It didn't solve my problem though, I have a 1st-gen Air with i5-6200 and it doesn't sleep nor shut down, even with SS03 and SS04 disabled, even with all USB2.0 files up this thread. Can somebody help me with this? It's really annoying. Also I would love to disable HS07 but even if I delete it from SSDT and injectors, it still appears, conflicting with my BT dongle. I've tried latest 5.3 OpenCore. Help will be really appreciated :) Here's the zip, to update bios you should unarchive it to FAT32 usb flash drive and boot it from F12 menu: (google drive)[https://drive.google.com/file/d/1ZIdW7u5lxNpa0JA-6LJzuEien3uV3yWH/view?usp=sharing]

For shutdown and sleep, use the latest version of this project, and add this two usb patches https://www.insanelymac.com/forum/topic/339035-pre-release-macos-catalina/?do=findComment&comment=2676253. When I add the broadcom network card, I  got the same issues with you, the built-in bluetooth confilct with the one I added. I just edit the usb-injectall kexts file with text editor, and find all things related to HS07, delete them and save. After rebot, the built-in bluetooth dispeared, and broadcom one got to work.

**Comment by jiangfeiyu** [comment]
@ johnnync13 @bossoq @ dawg115 @ xuyoji 
I also find my HDMI port is not working. But, it works on type-c hub's HDMI port.

**Comment by FallenChromium** [comment]
@jiangfeiyu my HDMI works just fine. A09, i5, v5.3

**Comment by jiangfeiyu** [comment]
> @jiangfeiyu my HDMI works just fine. A09, i5, v5.3
hi,my version is 10.15.1

**Comment by johnnync13** [comment]
If you want to contribute, make a pull request.  You are free to modify the code.  Lately I'm very busy and I can't meet the needs of those who have the laptop

**Comment by xuyoji** [comment]
> For USB issue, I still cannot find any way to fix this.
> 
> HS01//SS01 => USB3 => Right Port => Type 3
> HS03//SS03 => USB-C + SW => Right USB-C Port => Type 9
> HS04//SS04 => USB3 => Left Port => Type 3
> HS05 => Internal Webcam => Type 255 // Not tested since I broke my ribbon cable already. It rarely works in Windows.
> HS07 => Internal Bluetooth (via soldered M.2 Intel WiFi) => Type 255 (For me, I disabled this port since bluetooth is not working in macOS anyway, except VM firmware injection method)
> 
> Interestingly, I found SS02 in DSDT which I think it's connected to M.2 B Key (WWAN Slot). I plan to use this port for Bluetooth on BCM94360.
> 
> For my Scenario (Xiaomi Air 13.3 i7-6500U with A09 on macOS 10.14.6)
> 
> 1. Disable SS03 and SS04
> 
> * First Sleep via menu => worked
> * First Sleep via clamshell close => worked but USB not functioned after wakeup. We should try to debug on _PRW // _GPE // LID0 // other EC call methods.
> * Second Sleep (no reboot) both menu and clamshell result in sleep failure. Screen turned black, Power LED stayed on, USB Power cutoff, No keyboard lighted, Fans spin.
> * Shutdown => worked // Laptop completely shutdown. No power led.
> 
> 1. Enable any SS03 or SS04 results in sleep, shutdown not working.
>    `pmset -g log` show Sleep Failure with some random code.
> 
> I think for i5 model with A09, disable only SS04 solve the problem. However, i7 model (with A06 or A09) needs to disable both SS03 and SS04 which partially solve the problem. This is weird since both i5 and i7 models use same BIOS and I don't think XiaoMi change PCB design for both 2 models.

@jiangfeiyu My HDMI is working now by  using setup_var method and the config.plist config provided by bossoq. Use this efi file to boot from a flash disk. https://github.com/datasone/grub-mod-setup_var And just input the setup_var command above. After that, make sure your config.plist fixed by the above code.

**Comment by xuyoji** [comment]
@bossoq Just using all ports with USBinjectAll(except HS07 baned by clover boot option **uia-exclude=HS07**, because I need to disable the on-board bluetooth. @FallenChromium it is also what you need), my Mi book air works fine on sleep(even for sleep many times and long time sleep). However, shutdown is not work. I find [this](https://github.com/coisadepro/5470-shutdown-patch) project to replace shudown command with reboot command, and modify the clover boot file to make it shudown when there's a indicator file in the EFI folder. It works on 10.15's command line by typing reboot or shudown. However, it doesn't work on 10.15's user interface. By my test, 10.15 close the permission to write on the EFI partition after click the shutdown button on the user interface. Therefore, I write a script to creat a indicator file each time when login to solve the problem.(Cpoy it to a new file whose name is initial.command and use **chmod +x initial.command** to make it  executable) After install [this](https://github.com/coisadepro/5470-shutdown-patch) patch(need to run **sudo mount -uw /** and **killall Finder** before installation to completely close SIP on 10.15) and add my script to the login item, the shutdown just runs fine. (Reboot will also be treated as shudown, if you really want to reboot, using termial and type **sudo shutdown -r now**)
`#hide this script
osascript <<EOF
tell application "Finder"
set visible of process "Terminal" to false
end tell 
EOF

#mount the EFI, and create the indicator file for clover
#to make it shutdown when find the file
cd /sbin/ 
efi_dir=$(echo **YOUPASSWORD** | sudo -S bash mount_efi.sh) 
cd $efi_dir/EFI 
echo 1 > .PENDING_SHUTDOWN
exit 0`
Replace **YOURPASSWORD** before using it. Better to set terminal preference-profiles-when the shell exits-close the window.
I'll try to modify and rebuild the [patch](https://github.com/coisadepro/5470-shutdown-patch) to make it runs without additional script.

**Comment by xuyoji** [comment]
> @jiangfeiyu My HDMI is working now by using setup_var method and the config.plist config provided by bossoq. Use [this](https://github.com/datasone/grub-mod-setup_var) efi file to boot from a flash disk. And just input the setup_var command above. After that, make sure your config.plist fixed by the above code.
> P.S. HDMI audio seems still not working.
By many tries, HDMI audio finally fixed by change DVMT to 96mb rather than 128mb. Larger DVMT make the HDMI audio breakdown, it's really a magic.

**Comment by jiangfeiyu** [comment]
@xuyoji Thank you very much

**Comment by jiangfeiyu** [comment]
@xuyoji  My HDMI port output shows something wrong，Similar to contour

**Comment by xuyoji** [comment]
@jiangfeiyji Do you use HiDPI? I have encountered the same problem with yours,  and fix it accidentally. Turn off HiDPI and see the effect.  If it recover to normal,  try to use a different HiDPI setting.

**Comment by jiangfeiyu** [comment]
> @jiangfeiyji Do you use HiDPI? I have encountered the same problem with yours, and fix it accidentally. Turn off HiDPI and see the effect. If it recover to normal, try to use a different HiDPI setting.

thinks you!  turn off HiDPI , it recover to normal

**Comment by xuyoji** [comment]
@jiangfeiyji You are welcome.  May be you can use Hackintool instead of  one key HiDPI to make it work without contour.

**Comment by johnnync13** [comment]
https://github.com/xzhih/one-key-hidpi

**Comment by johnnync13** [comment]
shutdown work https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/5.5 ????

**Comment by xuyoji** [comment]
> shutdown work https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/5.5 ????

@johnnync13 Thanks for your effort johnny! You are so kind. 
However, with the newest EFI file on my mi book, shutdown is still not working. And the broadcom bluetooth will break down after sleep too. What's more, it seems that the new touchpad driver is not 
as stable as the old one. It will break down sometimes.

**Comment by Nxys** [comment]
> shutdown work https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/5.5 ????

Yes,shutdown  work.Thanks a lot!

**Comment by johnnync13** [comment]
Are you any problem with the latest releases?

**Comment by jiangfeiyu** [comment]
> Are you any problem with the latest releases?
hi,my version is 10.15.2，efi v5.8  ,shutdown don't  work

**Comment by johnnync13** [comment]
@jiangfeiyu What is the last EFI that shutdown works?

**Comment by johnnync13** [comment]
@Nxys which version can you shutdown

**Comment by mn19941219** [comment]
> @bossoq Just using all ports with USBinjectAll(except HS07 baned by clover boot option **uia_exclude=HS07**, because I need to disable the on-board bluetooth. @FallenChromium it is also what you need), my Mi book air works fine on sleep(even for sleep many times and long time sleep). However, shutdown is not work. I find [this](https://github.com/coisadepro/5470-shutdown-patch) project to replace shudown command with reboot command, and modify the clover boot file to make it shudown when there's a indicator file in the EFI folder(the indicator file will be created when click the shutdown button or when clover detect it when boot). It works on 10.15's command line by typing reboot or shudown. However, it doesn't work on 10.15's user interface. By my test, 10.15 close the permission to write on the EFI partition after click the shutdown button on the user interface. Therefore, I write a script to creat a indicator file each time when login to solve the problem.(Cpoy it to a new file whose name is initial.command and use **chmod +x initial.command** to make it executable) After install [this](https://github.com/coisadepro/5470-shutdown-patch) patch(need to run **sudo mount -uw /** and **killall Finder** before installation to completely close SIP on 10.15) and add my script to the login item, the shutdown just runs fine. (Reboot will also be treated as shudown, if you really want to reboot, using termial and type **sudo shutdown -r now**)
> 
> ```
> #hide this script
> osascript <<EOF
> tell application "Finder"
> set visible of process "Terminal" to false
> end tell 
> EOF
> 
> #mount the EFI, and create the indicator file for clover
> #to make it shutdown when find the file
> cd /sbin/ 
> efi_dir=$(echo YOURPASSWORD | sudo -S bash mount_efi.sh) 
> cd $efi_dir/EFI 
> echo 1 > .PENDING_SHUTDOWN
> exit 0
> ```
> 
> Replace **YOURPASSWORD** before using it. Better to set terminal preference-profiles-when the shell exits-close the window.
> I'll try to modify and rebuild the [patch](https://github.com/coisadepro/5470-shutdown-patch) to make it runs without additional script latter.

你好，关于关机不断电的问题，现在依然可以按照上面的步骤处理吗，屏蔽掉HS07的蓝牙，装上补丁，加入你的代码。目前有没有更好的办法了
