### ISSUE TITLE
Problems with the last release

### ISSUE THREAD

**Issue by kiptilyi** [johnnync13/Xiaomi-Notebook-Air-1Gen#14]
Hello @johnnync13!
Last release is cool! Thanks!
But I have some problems:
1. Shutdown is not working;
2. Brightness keys is not working;
3. When I close and then open lid - usb ports is not working.

**OS version: 10.14.5
Bios version: A09**

**Comment by Tomas1861** [comment]
the same question with kiptilyi,   all USB ports can‘t work  after sleep and wake up

**Comment by Tomas1861** [comment]
@johnnync13 ，the same question with kiptilyi, all USB ports can‘t work after sleep and wake up
