### ISSUE TITLE
Exclusive Edition shutdown

### ISSUE THREAD

**Issue by dawg115** [johnnync13/Xiaomi-Notebook-Air-1Gen#17]
Shutdown does not work on Xiaomi Notebook Air 13.3 2016 Exclusive Edition (i7-6500U).
I've heard A09 BIOS update fixes that, but I don't know if it will work with my CPU.

**Comment by johnnync13** [comment]
The problem is with power USB with usb3.0

**Comment by dawg115** [comment]
i see, is there any way to fix this?
