### ISSUE TITLE
Shutdown but cannot be powered off, the power light is still on

### ISSUE THREAD

**Issue by jiangfeiyu** [johnnync13/Xiaomi-Notebook-Air-1Gen#25]
After using your efi, my XiaoMi-NoteBook-Air-1Gen still has the problem that the power cannot be disconnected.
How can I solve it ? 
MacOS version: cataline 15.1
thanks you！

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/issues/12
