### ISSUE TITLE
Bluetooth is ready to use

### ISSUE THREAD

**Issue by iErics** [johnnync13/Xiaomi-Notebook-Air-1Gen#27]
Bluetooth is now available on 10.15 systems
[https://github.com/zxystd/IntelBluetoothFirmware](url)
![截屏2020-01-04上午9 13 01](https://user-images.githubusercontent.com/42070668/71769333-be085280-2f5a-11ea-9c36-f2433d6cacab.png)

**Comment by johnnync13** [comment]
I know! I'm waiting for anothers improvements to update EFI.

**Comment by johnnync13** [comment]
@iErics if you want to do pull request?

**Comment by iErics** [comment]
> @iErics if you want to do pull request?

I will wait for your improvement.

**Comment by iErics** [comment]
[https://github.com/zxystd/IntelBluetoothFirmware(url)

**Comment by iErics** [comment]
https://github.com/zxystd/IntelBluetoothFirmware

**Comment by iErics** [comment]
The link I gave may have some problems, this is the new link: https://github.com/zxystd/IntelBluetoothFirmware
