### ISSUE TITLE
battery percentage

### ISSUE THREAD

**Issue by nachopavon** [johnnync13/Xiaomi-Notebook-Air-1Gen#28]
Hi, First thanks for this repo.
I have noticed that battery percent is not showing up in the top bar since version 5.3. Could it be easy to fix?
Thanks again

**Comment by johnnync13** [comment]
Hola! Es raro! miraré a ver @nachopavon

**Comment by johnnync13** [comment]
@nachopavon funciona ahora?

**Comment by nachopavon** [comment]
No, he instalado la v6.0 y sigo sin ver la bateria, me funcionaba bien en la 5.3, pero después he instalado todas las versiones y no se visualiza, además en las preferencias del sistema sale la batería al 0%...
