### ISSUE TITLE
Is it supported mac 15.2

### ISSUE THREAD

**Issue by SummerVibes** [johnnync13/Xiaomi-Notebook-Air-1Gen#29]
I replace my efi with this one, but I stuck in "++++++++++++++".

**Comment by johnnync13** [comment]
yeah works well!

**Comment by ymlgithub** [comment]
> I replace my efi with this one, but I stuck in "++++++++++++++".

I also stuck in "++++++++++++++"，have you solved it？

**Comment by SummerVibes** [comment]
Sorry, I didn't. asxxw741 Email:asxxw741@qq.com Signature is customized by Netease Mail Master On 01/30/2020 00:39, 杨明亮 wrote: I replace my efi with this one, but I stuck in "++++++++++++++". I also stuck in "++++++++++++++"，have you solved it？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ymlgithub** [comment]
@johnnync13 Maybe you forget to update some file?
