### ISSUE TITLE
Bluetooth and shutdown conflict

### ISSUE THREAD

**Issue by jiangfeiyu** [johnnync13/Xiaomi-Notebook-Air-1Gen#31]
If the Bluetooth works normally, it cannot shutdown. 
If the Bluetooth driver is removed, it can shutdown.

**Comment by johnnync13** [comment]
thanks to feedback! @jiangfeiyu. One question, what success when you shutdown?

**Comment by jiangfeiyu** [comment]
> thanks to feedback! @jiangfeiyu. One question, what happens when you shutdown?

power cannot turn off
