### ISSUE TITLE
intel wifi can be connected, but it is not perfect, many problems such as restart

### ISSUE THREAD

**Issue by jiangfeiyu** [johnnync13/Xiaomi-Notebook-Air-1Gen#32]
<img width="667" alt="截屏2020-02-06上午1 52 03" src="https://user-images.githubusercontent.com/5492375/73869425-2eb9cc00-4885-11ea-9772-9096ffe66d20.png">

**Comment by xiaoliu0802** [comment]
我的没有WiFi，弄不出来，不知道怎么回事
