### ISSUE TITLE
some issues in clover and OC

### ISSUE THREAD

**Issue by ymlgithub** [johnnync13/Xiaomi-Notebook-Air-1Gen#34]
I've tried to install mac 15.3 with your latest version，but I found some issues:
1. When using clover, I stuck in +++++++++++++++ at beginning unless I remove 
```
<key>KernelPm</key>
<false/>
```
2. there is no HDMI output with clover.
3. I cannot adjust screen brightness with opencore.

**Comment by johnnync13** [comment]
with hackintool you could fix some issues
