### ISSUE TITLE
the latest version issue 

### ISSUE THREAD

**Issue by mn19941219** [johnnync13/Xiaomi-Notebook-Air-1Gen#36]
download the latest version （clover-efi）
not worked
1.touchpad
2shutdown
3.Bluetooth
4.sleep
-------
i think to solve these issue we need make a new usbports.kext

**Comment by mn19941219** [comment]
**good news:**
Issue 1.2.3 has already fixed issue 4 almost fixed
**method：**

you just download this _usbports.kext_ put in \EFI\CLOVER\KEXT\OTHER and delete  _USBInjectAll.kext_,then reboot.
[USBPorts.kext.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4209021/USBPorts.kext.zip)
**now :**
1. laptop can shutdown and power off
2. bluetooth can work good and no need reboot to windows to active 
3. touchpad can work well with one two three four figure
4. sleep is work well but u can not close the lid into sleep

<img width="668" alt="QQ20200216-023446@2x" src="https://user-images.githubusercontent.com/45319384/74595727-ebbade00-5066-11ea-9455-93f232a5a627.png">
<img width="668" alt="QQ20200216-025031@2x" src="https://user-images.githubusercontent.com/45319384/74595747-1dcc4000-5067-11ea-8659-7d2216995c14.png">

#31 #25

**Comment by yncxfan** [comment]
> **好消息：**
> 问题1.2.3已修复问题4几乎已解决的
> **方法：**
> 
> 您只需下载\ _efi_ \ _clover_ \ _kext_ \ _other下的usbports.kext_，然后删除 _USBInjectAll.kext_，然后重新启动即可。
> [USBPorts.kext.zip ](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4209021/USBPorts.kext.zip)
> **现在：**
>
What is the Mac version you are using now?

**Comment by mn19941219** [comment]
> > **好消息：**
> > 问题1.2.3已修复问题4几乎已解决的
> > **方法：**
> > 您只需下载\ _efi_ \ _clover_ \ _kext_ \ _other下的usbports.kext_，然后删除 _USBInjectAll.kext_，然后重新启动即可。
> > [USBPorts.kext.zip ](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4209021/USBPorts.kext.zip)
> > **现在：**
> 
> What is the Mac version you are using now?

10.5.3

**Comment by mn19941219** [comment]
but sleep and wake can only use one time after boot,the second time cant sleep and wake,i saw pcbeta bbs said this is the problem of 10.15.2 and 10.15.3, some people update to 10.15.4 to solve this issue ,but after i update Mac OS, it's fixed

**Comment by gezimos** [comment]
> **good news:**
> Issue 1.2.3 has already fixed issue 4 almost fixed
> **method：**
> 
> you just download this _usbports.kext_ put in \EFI\CLOVER\KEXT\OTHER and delete _USBInjectAll.kext_,then reboot.
> [USBPorts.kext.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4209021/USBPorts.kext.zip)
> **now :**
> 
> 1. laptop can shutdown and power off
> 2. bluetooth can work good and no need reboot to windows to active
> 3. touchpad can work well with one two three four figure
> 4. sleep is work well but u can not close the lid into sleep
> 
> <img alt="QQ20200216-023446@2x" width="668" src="https://user-images.githubusercontent.com/45319384/74595727-ebbade00-5066-11ea-9455-93f232a5a627.png">
> 
> <img alt="QQ20200216-025031@2x" width="668" src="https://user-images.githubusercontent.com/45319384/74595747-1dcc4000-5067-11ea-8659-7d2216995c14.png">
> 
> #31 #25

I Tried this, but Shutdown still not working for me. I'm on 10.15.3.
Touchpad works, bluetooth shows, turns on but can't connect to my mx master.

Any idea?
