### ISSUE TITLE
External Display

### ISSUE THREAD

**Issue by gezimos** [johnnync13/Xiaomi-Notebook-Air-1Gen#37]
Hi Johhny & everybody contributing to this..
I've installed Catalina on Mi air 13 (1st gen) and pretty much everything that I need works.
For wifi i'm using dongle, for mouse dongle. I haven't managed to install the intel wifi kext via terminal (i'm very noob).

But external display on hdmi is not working. Does anybody have any idea?
I looked at the guides and didn't mention external displays.

Thanks in advance, sorry if the question is stupid).

**Comment by johnnync13** [comment]
With hackintool. You should see what port change and send me config.plist

**Comment by gezimos** [comment]
Thanks for your quick answer. I'm very new to this, so hopefully I'm doing it right.
I have attached screenshots from hackintool, because i'm not sure what u are looking exactly.
Have included the config.plist (also the full efi folder).

Some more info: i used the guide from sakoula and efi from you. Only change i think is the usb kext i got from that other thread, because laptop wasn't powering off fully.

[HT + config.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4240485/HT.%2B.config.zip)

**Comment by gezimos** [comment]
Hey man, solved the issues by using mini dp port to hdmi adapter. So hdmi not working for me is not a big deal anymore. So don't even waste time on that because it seems i'm the only one with that problem.

If u could help with the powering off issue it would be perfect.

Your USBInjectAll.kext makes trackpad work perfectly, all usb ports, only thing doesn't work is powering off. So i used the kext below and powering off works fine, but trackpad has a lot of bugs and usb 3 items don't work anymore.
[https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/issues/36#issuecomment-586644605](url)

U can still look at my config above.

**Comment by johnnync13** [comment]
In hackintool there is an option to conver dp->hdmi without any adapter...

**Comment by gezimos** [comment]
I tried looking for convert dp to hdmi, but found it nowhere on Hackintool. I have latest version.

I managed to combine USBinjectall with some USBportskext and have the power down and usb 3.0 working at same time. But there are still some trackpad bugs with this option.

Meanwhile DP to HDMI display is working okay, only bug is the display loses like 10-20% brightness after I enter the password. I tried installing Brightness Monitor, my display supports ddc but it's not helping.

Thanks a bunch.

**Comment by johnnync13** [comment]
@gezimos ![Captura de pantalla 2020-02-25 a las 0 25 03](https://user-images.githubusercontent.com/22727137/75200163-44743000-5765-11ea-9611-2c20dac15625.png)

**Comment by jimmymitlavigne** [comment]
Many thanks for Johny & everybody contributing to this. THANKS Johnny!
@gezimos  hey i have the same lap Mi air 13 (1st gen)
did you fix the wifi problem? which app did you use the dongle wifi.
may i have a copy,

**Comment by iErics** [comment]
> I tried looking for convert dp to hdmi, but found it nowhere on Hackintool. I have latest version.
> 
> I managed to combine USBinjectall with some USBportskext and have the power down and usb 3.0 working at same time. But there are still some trackpad bugs with this option.
> 
> Meanwhile DP to HDMI display is working okay, only bug is the display loses like 10-20% brightness after I enter the password. I tried installing Brightness Monitor, my display supports ddc but it's not helping.
> 
> Thanks a bunch.

Did you solve this problem?

**Comment by gezimos** [comment]
@johnnync13 Thanks a lot for your help man, but I didn't manage to get it to work using those settings with hackintool.

@jimmymitlavigne I didn't bother with wifi, I'm using a random wifi dongle that I installed using an "all in one wifi dongle drivers for macos" don't remember the name, try googling with that.

@iErics Which one exactly?

**Comment by iErics** [comment]
> @johnnync13 Thanks a lot for your help man, but I didn't manage to get it to work using those settings with hackintool.
> 
> @jimmymitlavigne I didn't bother with wifi, I'm using a random wifi dongle that I installed using an "all in one wifi dongle drivers for macos" don't remember the name, try googling with that.
> 
> @iErics Which one exactly?

HDMI

**Comment by gezimos** [comment]
@iErics No I wasn't able to use hdmi directly. I'm using the xiaomi mini dp dongle that I had, and borrowed a mini dp to hdmi dongle from a friend.

**Comment by jimmymitlavigne** [comment]
> @johnnync13 Thanks a lot for your help man, but I didn't manage to get it to work using those settings with hackintool.
> 
> @jimmymitlavigne I didn't bother with wifi, I'm using a random wifi dongle that I installed using an "all in one wifi dongle drivers for macos" don't remember the name, try googling with that.
> 
> @iErics Which one exactly?

  thanks for your reply! the dongle wifi works for me now. but still have the shutdown problem, power didn't off
