### ISSUE TITLE
A problem using the Wifi driver on other computers

### ISSUE THREAD

**Issue by MEMZSONBILI** [johnnync13/Xiaomi-Notebook-Air-1Gen#38]
Hello there,
I am using the third generation (8130U) version of the Xiaomi notebook aIr. I want to use the Wi-Fi driver on this machine (same network card model is 8265AC, MacOS system is 10.15.1), I changed the BSSID and PWD, but encountered a problem:
Loading the driver directly will report the error:
failed to load-(libkern / kext) dependency load failed; check the system / kernel logs for errors or try kextutil (8).
If the driver is loaded after loading IO80211FamilyV2.kext, it will have other failures: Wi-Fi is OK, but it will restart automatically after a few seconds.
What should I do?

**Comment by johnnync13** [comment]
Nothing. You should wait the new releases...
