### ISSUE TITLE
excuse me, can u show something is not working? 

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [johnnync13/Xiaomi-Notebook-Air-1Gen#39]
there's something working, how about else not working.

**Comment by iErics** [comment]
> there's something working, how about else not working.

目前

> there's something working, how about else not working.

目前只有独显误解，WiFi正在开发中，已经可以联网。其它都正常使用。

**Comment by jimmymitlavigne** [comment]
> > there's something working, how about else not working.
> 
> 目前只有独显无解，WiFi正在开发中，已经可以联网。其它都正常使用。

我的关不了机 你有碰到这个情况吗  偶尔会自动重启

**Comment by lollipopeekaboo** [comment]
> > > there's something working, how about else not working.
> > 
> > 
> > 目前只有独显无解，WiFi正在开发中，已经可以联网。其它都正常使用。
> 
> 我的关不了机 你有碰到这个情况吗 偶尔会自动重启
你们用的是哪个版本？我安装了10.15.2之后，合盖唤醒之后usb无法使用，wifi搞了之后还是无法联网~

**Comment by lollipopeekaboo** [comment]
> > > there's something working, how about else not working.
> > 
> > 
> > 目前只有独显无解，WiFi正在开发中，已经可以联网。其它都正常使用。
> 
> 我的关不了机 你有碰到这个情况吗 偶尔会自动重启

你们用的是哪个版本？我安装了10.15.2之后，合盖唤醒之后usb无法使用，wifi搞了之后还是无法联网~

**Comment by jimmymitlavigne** [comment]
> > > > there's something working, how about else not working.
> > > 
> > > 
> > > 目前只有独显无解，WiFi正在开发中，已经可以联网。其它都正常使用。
> > 
> > 
> > 我的关不了机 你有碰到这个情况吗 偶尔会自动重启
> 
> 你们用的是哪个版本？我安装了10.15.2之后，合盖唤醒之后usb无法使用，wifi搞了之后还是无法联网~

我用的是10.15.3   wifi我的也无法联网

**Comment by iErics** [comment]
> > > > there's something working, how about else not working.
> > > 
> > > 
> > > 目前只有独显无解，WiFi正在开发中，已经可以联网。其它都正常使用。
> > 
> > 
> > 我的关不了机 你有碰到这个情况吗 偶尔会自动重启
> 
> 你们用的是哪个版本？我安装了10.15.2之后，合盖唤醒之后usb无法使用，wifi搞了之后还是无法联网~

wifi目前处于早期开发阶段，不建议使用。

**Comment by iErics** [comment]
> > > there's something working, how about else not working.
> > 
> > 
> > 目前只有独显无解，WiFi正在开发中，已经可以联网。其它都正常使用。
> 
> 我的关不了机 你有碰到这个情况吗 偶尔会自动重启

无法关机是左侧USB3.0导致，删除左侧USB3.0即可。

**Comment by jimmymitlavigne** [comment]
> 无法关机是左侧USB3.0导致，删除左侧USB3.0即可。

感谢回复！怎么删除？ 删除过后左边USB还可以使用吗
