### ISSUE TITLE
hdmi external display

### ISSUE THREAD

**Issue by nompangyi19** [johnnync13/Xiaomi-Notebook-Air-1Gen#41]
Thanks to you, I was able to install Catalina! thank you so much! There is one unfortunate thing. Can't I use HDMI port? And when I try to use hackintool it crashes.

**Comment by johnnync13** [comment]
@nompangyi19 try de latest version

**Comment by nompangyi19** [comment]
> @nompangyi19 try de latest version

ok! thank you! you are genius!

**Comment by nompangyi19** [comment]
> @nompangyi19 try de latest version
ok! thank you! you are genius!
