### ISSUE TITLE
I cannot manage to successfully install at all!

### ISSUE THREAD

**Issue by FeKgr** [johnnync13/Xiaomi-Notebook-Air-1Gen#42]
I tried many different sub versions of Catalina and High Sierra but none of them seem to work on my machine! 
Usually I am stuck at either [this](https://ibb.co/cYN0ssx) or a line of this here: (++++++)

I tried each of the tested versions with either the Elfi folder from your github or the files from the EFIOC in my EFI folder but sadly it still does not work out. 
I even exchanged my NVMe ssd and replaced it with a m.2 sata one but still no luck.
I used gibMacOS-master to download and copy onto usb...

Can someone please help me troubleshoot?

**Comment by FeKgr** [comment]
Or please just someone post the exact configuration used for their air 13.3 6200u so I can try that one.

**Comment by UnknownH** [comment]
Same issue here, not being able to install catalina at all following the steps in the readme.. Why was this issue closed?

**Comment by johnnync13** [comment]
https://youtu.be/FgJucJKbn2Y
