### ISSUE TITLE
battery problem in last release v7.1.1

### ISSUE THREAD

**Issue by jimmymitlavigne** [johnnync13/Xiaomi-Notebook-Air-1Gen#43]
Thanks for you help.
1. Can't turn this on : Show battery status in menu bar . and no battery icon in menu, no charging
2. still can't power off 
when i switch back to v7.0.2 , battery problem 1 solved, and battery icon back
mac os 10.15.3

**Comment by johnnync13** [comment]
Do you have trackpad menu? If not appear this, not appear battery

**Comment by jimmymitlavigne** [comment]
> Do you have trackpad menu? If not appear this, not appear battery
Thanks for your reply.
after test in v7.1.2, problem still. and yes, no trackpad menu too.
1. Can't turn this on : Show battery status in menu bar . and no battery icon in menu, no charging
2. can't power off
3. the brightness is very high. open in like one percent bright menu, but still very bright
BTW the win and alt button seems switched in v7.1.1 and v7.1.2

**Comment by johnnync13** [comment]
@jimmymitlavigne only on clover or oc too?

**Comment by jimmymitlavigne** [comment]
i only test in clover

**Comment by johnnync13** [comment]
@jimmymitlavigne try v7.1.2

**Comment by jimmymitlavigne** [comment]
I tried in v7.1.2.
Problems 1,2,3. still have

**Comment by johnnync13** [comment]
I don't know why, because VoodooInput and VoodooPS2Controller are in efi. Do you rebuild cache with Hackintool?

**Comment by jimmymitlavigne** [comment]
I rebuild the cache in terminal, and rebooted.
I use the v7.0.2 now, don’t have problems 1,3

**Comment by johnnync13** [comment]
rebuild in Hackintool to enable gatekeeper

**Comment by nompangyi19** [comment]
> rebuild in Hackintool to enable gatekeeper
First of all, I want to say thank you. You are the best!
In 7.02, hackin tools did not work (clover).
This time I uploaded opencore. In 7.1.1, there is an error that the led of the power button does not turn off.

**Comment by johnnync13** [comment]
@nompangyi19 if you want to collaborate in this repository, you can. When the shutdown did It stop working?

**Comment by nompangyi19** [comment]
> @nompangyi19 if you want to collaborate in this repository, you can. When the shutdown did It stop working?
After shutdown, the fan runs weakly. It was not completely turned off. The power LED was not turned off.

**Comment by nompangyi19** [comment]
> @nompangyi19 if you want to collaborate in this repository, you can. When the shutdown did It stop working?
7.1.2 I also tried clover. In opencore, the battery state worked. In Clover, the battery menu disappears.

**Comment by johnnync13** [comment]
@nompangyi19 try if shutdown works in clover, on efi repository not in releases

**Comment by nompangyi19** [comment]
> @nompangyi19 try if shutdown works in clover, on efi repository not in releases
The shutdown problem is the same for both clover and open core.

**Comment by johnnync13** [comment]
@nompangyi19 try the last commit https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/tree/a824a61fabeda1ed9306bee420c20fe859ef6c6f
