### ISSUE TITLE
Open core, clover Shutdown issue, clover cannot run out of battery and shut down issue

### ISSUE THREAD

**Issue by nompangyi19** [johnnync13/Xiaomi-Notebook-Air-1Gen#44]
I'm using open-core, your wonderful work now. But I also tested the clover using usb. Once I ran the clover based on the commit that ran on 7.1.2, the shutdown was impossible. There is no battery level.

After that, I tested the newly uploaded 7.1.3. Thank you for making a great open core. First of all, what I can do is to test it, so I also tested clover with open core and usb boot with hard boot.

Unfortunately, not all of them seem to have been fixed. Both Open Core and Clover were unable to shut down, and fans and leds remained the same. One difference is that the battery level in the open core can be checked. However, the battery level cannot be checked with the clover.

Thank you.

**Comment by johnnync13** [comment]
I move to #45
