### ISSUE TITLE
Testing 7.1.6

### ISSUE THREAD

**Issue by dpunx** [johnnync13/Xiaomi-Notebook-Air-1Gen#45]
Hi,

Here the problems that I've found.

On clover:
- [x] Battery stay at 0% and can't show icon
- [x] Not power off
- [x] HDMI video/audio not work

On OC:
- [x] Brightness not work (keywords and control panel not show)
- [x] Not power off

Thanks fot your work

**Comment by johnnync13** [comment]
in clover can you shutdown?

**Comment by johnnync13** [comment]
@brightness is fixed

**Comment by johnnync13** [comment]
@dpunx HDMI works on OC?

**Comment by dpunx** [comment]
Yes, on OC HDMI works well and now the brightness works again!

Clover & OC:
- Not shutdown

Clover:
- No HDMI
- No Battery stats

Thanks!

**Comment by johnnync13** [comment]
I think that I will not update clover, seems a lot problems. OC is better

**Comment by johnnync13** [comment]
@dpunx on clover can you shutdown?

**Comment by nompangyi19** [comment]
> @dpunx on clover can you shutdown?

not shutdown

**Comment by johnnync13** [comment]
@dpunx can you take a photo on usb in Hackintool and in Power?

**Comment by 977844579** [comment]
> @dpunx，你可以在哈克工具和电源的usb上拍照吗？

![WX20200402-164747](https://user-images.githubusercontent.com/41711995/78229190-3b177980-7502-11ea-88ce-a9687cafbd78.png)
![WX20200402-165058](https://user-images.githubusercontent.com/41711995/78229195-3d79d380-7502-11ea-8a7f-b6bdca8ffa2f.png)
Do you need this information? Thank you for your efforts.

**Comment by johnnync13** [comment]
This is no correct... I would try to fix
