### ISSUE TITLE
Tsting 7.1.8

### ISSUE THREAD

**Issue by nompangyi19** [johnnync13/Xiaomi-Notebook-Air-1Gen#47]
Awesome!  Are you a genius ?!  I tested opencore.  Shutdown problem is solved!  Report new issues.  Sleep and wake do not work.

**Comment by johnnync13** [comment]
If you unlock CFG lock you should works sleep and wake

**Comment by 977844579** [comment]
You are amazing, he is almost perfect! Thank you. I am also using it.

**Comment by johnnync13** [comment]
https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/post-install/msr-lock

If you send me a backup bios a09, I could make script

**Comment by nompangyi19** [comment]
> https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/post-install/msr-lock
> 
> If you send me a backup bios a09, I could make script

**Comment by nompangyi19** [comment]
[VFBI0A09.exe.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4422964/VFBI0A09.exe.zip)

this file?

**Comment by johnnync13** [comment]
nop. Yo should do a backup .fd https://www.win-raid.com/f16-BIOS-Modding-Guides-and-Problems.html

**Comment by johnnync13** [comment]
@nompangyi19 could works! I am researching

**Comment by johnnync13** [comment]
@nompangyi19 yeaaah! I've been able to extract the information of bios!
[Setup IFR.txt](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4423326/Setup.IFR.txt)

**Comment by nompangyi19** [comment]
> @nompangyi19 yeaaah! I've been able to extract the information of bios!
> [Setup IFR.txt](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4423326/Setup.IFR.txt)
> I could make an experiment.
Excellent!  It's getting perfect!

**Comment by johnnync13** [comment]
@nompangyi19 you have files on BIOS, and tutorial on README
