### ISSUE TITLE
Problems using OC installation

### ISSUE THREAD

**Issue by CoderSunflower** [johnnync13/Xiaomi-Notebook-Air-1Gen#48]
When I installed (using OpenCore) Catilina 10.15.4, I got an installation error.I installed Catilina using a second hard drive (SATA protocol).
The error is an error while verifying the firmware.
Can you help me?

Thank you for your EFI file.
Thank you very much

**Comment by rodion1322** [comment]
I too have same problem. But i try install on first sdd.
Catalina don't want install on AFPS (like say upgrade your mac and etc....)
Well... I make "Mac os extended" and it try installing
But after reboot i have same problem like @CoderSunflower

**Comment by johnnync13** [comment]
for ssd you must use APFS. I use clover to installation and OC for daily uses

**Comment by rodion1322** [comment]
Well may be help me. I have usb tplink wn725n for internet
I add kexts in OC EFI (RtWlanU, RtWlanU1827) for load installation
OC loaded it's kexts and i connected with wpa_supplicatn tool
But clover don't want load my kexts 🌵 (p.s I turn on InjectKext to "Yes")

**Comment by CoderSunflower** [comment]
> for ssd you must use APFS. I use clover to installation and OC for daily uses

What does it mean?
After using Clover to install the system successfully,then use OC boot instead of Clover boot.

**Comment by johnnync13** [comment]
@CoderSunflower Yes! Let's not forget, OPENCORE is still in beta
