### ISSUE TITLE
touch

### ISSUE THREAD

**Issue by flybeat246** [johnnync13/Xiaomi-Notebook-Air-1Gen#49]
Hi, on the last build 7.1.8 touch gestures do not work (no settings), only two-finger scrolling.
On build 7.0.2 the same thing.
what am I doing wrong?
![Снимок экрана 2020-04-03 в 02 40 50](https://user-images.githubusercontent.com/25207387/78347000-abe78180-7554-11ea-8f81-bacd2c2bbce1.png)
![Снимок экрана 2020-04-03 в 02 40 30](https://user-images.githubusercontent.com/25207387/78347012-af7b0880-7554-11ea-9a9d-d89fd6b2792f.png)

**Comment by johnnync13** [comment]
Use OpenCore

**Comment by flybeat246** [comment]
hi, open core the touchpad also does not work (
only 2 finger
![Снимок экрана 2020-04-03 в 08 22 35](https://user-images.githubusercontent.com/25207387/78377475-83777b80-7584-11ea-8b95-eec6d3f5d49b.png)

**Comment by johnnync13** [comment]
take photo on kexts installed

**Comment by flybeat246** [comment]
![Снимок экрана 2020-04-03 в 08 31 42](https://user-images.githubusercontent.com/25207387/78378268-98a0da00-7585-11ea-9ab3-9a36dc6f75c5.png)
![Снимок экрана 2020-04-03 в 08 31 14](https://user-images.githubusercontent.com/25207387/78378269-98a0da00-7585-11ea-82bc-6f50e9db0234.png)

**Comment by johnnync13** [comment]
Battery appears?

**Comment by flybeat246** [comment]
I don’t have a battery, I pulled it out.

shove and check?

**Comment by johnnync13** [comment]
seems to be okey.
Try this https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/v7.2.1

**Comment by flybeat246** [comment]
I used build 7.1.8.
Now I installed 7.2.1, rebooted and crashed on the boot screen (white apple is endless).
restored 7.1.8
Can the touchpad not work due to the fact that there is no battery?

**Comment by flybeat246** [comment]
Lol I connected the battery.
![Снимок экрана 2020-04-03 в 09 10 15](https://user-images.githubusercontent.com/25207387/78382001-fc79d180-758a-11ea-9642-cb2b73de34fc.png)

**Comment by flybeat246** [comment]
but I’m sitting at home, and I don’t want my battery to go bad permanently connected to the network.
what should I do?

**Comment by johnnync13** [comment]
Of course! To function trackpad, the battery have to be working

**Comment by flybeat246** [comment]
I inserted the battery, configured in the settings.
pulled out the battery. Settings do not open. but the trackpad and gestures work completely.
very good!)
