### ISSUE TITLE
How to switch to OC

### ISSUE THREAD

**Issue by jimmymitlavigne** [johnnync13/Xiaomi-Notebook-Air-1Gen#51]
Now, i use the clover, it is stable, but it can't shutdown, you guys say the OC is better, So i want to switch to OC.
Should i just copy  the EFIOC (opencore) folder from last release, and replace it to the EFI folder on the ESP？
after copy, should i rename the folder？
if running by OC, the folder on ESP name is EFI or  EFIOC ?

**Comment by rijianyunxi** [comment]
> Now, i use the clover, it is stable, but it can't shutdown, you guys say the OC is better, So i want to switch to OC.
> Should i just copy the EFIOC (opencore) folder from last release, and replace it to the EFI folder on the ESP？
> after copy, should i rename the folder？
> if running by OC, the folder on ESP name is EFI or EFIOC ?
if running by OC, the folder on ESP name is EFI

**Comment by johnnync13** [comment]
@jimmymitlavigne 
it is like clover.
Remove all folders in EFI Partition.
Copy EFIOC  to EFI Partition. Rename EFIOC to EFI
