### ISSUE TITLE
v7.2.3

### ISSUE THREAD

**Issue by 977844579** [johnnync13/Xiaomi-Notebook-Air-1Gen#52]
After I import it into the efi folder, it won't turn on anymore. Do you know why?I am using OpenCore

**Comment by rodion1322** [comment]
![B65A22E1-2F4D-4840-BD5B-86D7F6FCEEE7](https://user-images.githubusercontent.com/16890860/78455819-1a3d5880-76a9-11ea-8cb2-604de6eb1ce4.png)
I try disable it commit and work perfect

**Comment by 977844579** [comment]
Thanks, it started working. @rodion1322

**Comment by johnnync13** [comment]
@rodion1322 @977844579 you should to follow the tutorial of patching BIOS.
Xiaomi bios haven't enabled SpeedShift, CFG unlocked, MC unlocked, RTC unlocked, that is necessary to Hackintosh to better improvement

**Comment by 977844579** [comment]
@johnnync13 Do you have a modified tutorial about it? Thank you

**Comment by johnnync13** [comment]
See on readme

**Comment by 977844579** [comment]
Thank you

**Comment by 977844579** [comment]
@johnnync13 Thanks, I learned to change it to make it more perfect.
