### ISSUE TITLE
testing 7.2.4

### ISSUE THREAD

**Issue by nompangyi19** [johnnync13/Xiaomi-Notebook-Air-1Gen#56]
opencore

- touch pad no Work
- booting longtime

**Comment by nompangyi19** [comment]
> touch pad no Work

an

**Comment by rodion1322** [comment]
Touch pad not work +

About booting for me normal, fast.

**Comment by rodion1322** [comment]
Without voodooPS2Trackpad work, but says track pad not found and trackpad work like mouse only

**Comment by carpfish** [comment]
> Without voodooPS2Trackpad work, but says track pad not found and trackpad work like mouse only

Disable “add PNLF” patched can show battery pct and found track pad Preferences, then will Lose the function of change backlight .
