### ISSUE TITLE
The recovery server could not be contacted

### ISSUE THREAD

**Issue by abmfy** [johnnync13/Xiaomi-Notebook-Air-1Gen#63]
My notebook is Mi Air 13.3 1st Gen, i5-6200u. I chose to install from Windows with Clover. When I was trying to install macOS Mojave, it alerted that "The recovery server could not be contacted". Shouldn't macOS Mojave be able to be installed offline? How could I solve this?

**Comment by abmfy** [comment]
I tryed macOS High Sierra and the result was the same.


![Untitled](https://user-images.githubusercontent.com/20623941/79042046-e3c28900-7c26-11ea-85ac-974880088b4d.jpg)

**Comment by johnnync13** [comment]
@abmfy only works on catalina or Mojave

**Comment by abmfy** [comment]
> @abmfy only works on catalina or Mojave. GibMacOS requieres internet connection

Thanks. I created an installation media from macOS and it really works without showing the alert.
