### ISSUE TITLE
WiFi doesn't work

### ISSUE THREAD

**Issue by abmfy** [johnnync13/Xiaomi-Notebook-Air-1Gen#64]
Following the steps you gave [here](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/tree/master/WIFI) I downloaded "AppleIntelWiFi-Catalina.zip", edited "config.plist", executed the two commands and successfully load AppleIntelWiFi.kext. However, no difference seemed to appear. The WiFi option didn't appear in the Settings app and I could still not connect to my WiFi.
![截屏2020-04-12 下午8 14 17](https://user-images.githubusercontent.com/20623941/79068620-e2629080-7cfa-11ea-99e5-087085b19af8.png)
I also tried "AppleIntelWiFi-8265.zip" but failed to load it, with error message "/Users/abmfy/Downloads/AppleIntelWiFi.kext failed to load - (libkern/kext) dependency load failed; check the system/kernel logs for errors or try kextutil(8)."
My notebook is Mi Air 1st Gen, and from Windows's devices manager I find that my WiFi adapter is 8260.
I would appreciate it if you could offer me some help. Thanks a lot!

**Comment by 977844579** [comment]
https://c-t.work/s/5400197ab8b94a 4rgiwq
Need to modify *：
<key>BSSID</key>
				<string>******</string>
				<key>BSSID - 2</key>
				<string>KIMAX</string>
				<key>PWD</key>
				<string>*****</string>
1.put kext files on desktop
2.open terminal
3.cd ~/desktop
4.sudo chown -R root:wheel AppleIntelWiFi.kext
5.sudo chmod -R 755 AppleIntelWiFi.kext
6.sudo kextload -v AppleIntelWiFi.kext

**Comment by abmfy** [comment]
> https://c-t.work/s/5400197ab8b94a 4rgiwq
> Need to modify ：
> BSSID
> PWD
> 1.put kext files on desktop
> 2.open terminal
> 3.cd ~/desktop
> 4.sudo chown -R root:wheel AppleIntelWiFi.kext
> 5.sudo chmod -R 755 AppleIntelWiFi.kext
> 6.sudo kextload -v AppleIntelWiFi.kext

WOW, IT DOES WORK!!!
Now I'm replying to you using my WiFi!!!
You could imagine how excited I am now!
Thank you verrrrrrrrry much!

**Comment by flybeat246** [comment]
> > [https://ct.work/s/5400197ab8b94a](https://c-t.work/s/5400197ab8b94a) 4rgiwq 
> > Необходимо изменить ：
> > BSSID 
> > PWD 
> > 1.put kext-файлы на рабочем столе 
> > 2.open терминал 
> > 3.cd ~ / desktop 
> > 4.sudo chown -R root: wheel AppleIntelWiFi.kext 
> > 5.sudo chmod -R 755 AppleIntelWiFi.kext 
> > 6.sudo kextload -v AppleIntelWiFi.kext
> 
> ВАУ, ЭТО РАБОТАЕТ !!!
> Теперь я отвечаю вам, используя мой WiFi!
> Вы можете себе представить, как я сейчас взволнован!
> Большое спасибо verrrrrrrry!

how stable does it work?

**Comment by abmfy** [comment]
> > > [https://ct.work/s/5400197ab8b94a](https://c-t.work/s/5400197ab8b94a) 4rgiwq
> > > Необходимо изменить ：
> > > BSSID
> > > PWD
> > > 1.put kext-файлы на рабочем столе
> > > 2.open терминал
> > > 3.cd ~ / desktop
> > > 4.sudo chown -R root: wheel AppleIntelWiFi.kext
> > > 5.sudo chmod -R 755 AppleIntelWiFi.kext
> > > 6.sudo kextload -v AppleIntelWiFi.kext
> > 
> > 
> > ВАУ, ЭТО РАБОТАЕТ !!!
> > Теперь я отвечаю вам, используя мой WiFi!
> > Вы можете себе представить, как я сейчас взволнован!
> > Большое спасибо verrrrrrrry!
> 
> how stable does it work?

Sometimes it loses connection and need to be restarted. The rest of the time it works well, just a little slower than on Windows but acceptable.

**Comment by mn19941219** [comment]
> > > [https://ct.work/s/5400197ab8b94a](https://c-t.work/s/5400197ab8b94a) 4rgiwq
> > > Необходимо изменить ：
> > > BSSID
> > > PWD
> > > 1.put kext-файлы на рабочем столе
> > > 2.open терминал
> > > 3.cd ~ / desktop
> > > 4.sudo chown -R root: wheel AppleIntelWiFi.kext
> > > 5.sudo chmod -R 755 AppleIntelWiFi.kext
> > > 6.sudo kextload -v AppleIntelWiFi.kext
> > 
> > 
> > ВАУ, ЭТО РАБОТАЕТ !!!
> > Теперь я отвечаю вам, используя мой WiFi!
> > Вы можете себе представить, как я сейчас взволнован!
> > Большое спасибо verrrrrrrry!
> 
> how stable does it work?

youtube 1080P very stable

**Comment by flybeat246** [comment]
> > > > [https://ct.work/s/5400197ab8b94a](https://c-t.work/s/5400197ab8b94a) 4rgiwq
> > > > Необходимо изменить ：
> > > > BSSID
> > > > PWD
> > > > 1.put kext-файлы на рабочем столе
> > > > 2.open терминал
> > > > 3.cd ~ / desktop
> > > > 4.sudo chown -R root: wheel AppleIntelWiFi.kext
> > > > 5.sudo chmod -R 755 AppleIntelWiFi.kext
> > > > 6.sudo kextload -v AppleIntelWiFi.kext
> > > 
> > > 
> > > ВАУ, ЭТО РАБОТАЕТ !!!
> > > Теперь я отвечаю вам, используя мой WiFi!
> > > Вы можете себе представить, как я сейчас взволнован!
> > > Большое спасибо verrrrrrrry!
> > 
> > 
> > how stable does it work?
> 
> youtube 1080P very stable

how often is a network break?

**Comment by mn19941219** [comment]
> > > > > [https://ct.work/s/5400197ab8b94a](https://c-t.work/s/5400197ab8b94a) 4rgiwq
> > > > > Необходимо изменить ：
> > > > > BSSID
> > > > > PWD
> > > > > 1.put kext-файлы на рабочем столе
> > > > > 2.open терминал
> > > > > 3.cd ~ / desktop
> > > > > 4.sudo chown -R root: wheel AppleIntelWiFi.kext
> > > > > 5.sudo chmod -R 755 AppleIntelWiFi.kext
> > > > > 6.sudo kextload -v AppleIntelWiFi.kext
> > > > 
> > > > 
> > > > ВАУ, ЭТО РАБОТАЕТ !!!
> > > > Теперь я отвечаю вам, используя мой WiFi!
> > > > Вы можете себе представить, как я сейчас взволнован!
> > > > Большое спасибо verrrrrrrry!
> > > 
> > > 
> > > how stable does it work?
> > 
> > 
> > youtube 1080P very stable
> 
> how often is a network break?

only stable for one time...   the 2nd time when i use this kext ,break after 10 sec
