### ISSUE TITLE
OpneCore cannot work

### ISSUE THREAD

**Issue by wanghui15620608824** [johnnync13/Xiaomi-Notebook-Air-1Gen#65]
My Xiaomi Notebook 2016 13.3 cannot be started with OpenCore

**Comment by wanghui15620608824** [comment]
I can use Clover, but Clover installs dual system error

**Comment by johnnync13** [comment]
@wanghui15620608824 you have to do mod bios with the last version bios A09.
If not you have to lock cfg parametres in config.plist
