### ISSUE TITLE
Bluetooth doesn't work normally

### ISSUE THREAD

**Issue by abmfy** [johnnync13/Xiaomi-Notebook-Air-1Gen#66]
The Bluetooth settings appears in the Preferences Settings app. It seems detecting the devices nearby normally. However, when I tried connecting to my AirPods, it said "Connected" but there is a rotating circle on the right of it and I still cannot use my AirPods. Moreover, it seems that no devices can be connected and work normally.
Is the way I boot wrong? I'm now using your package of v7.2.5 and Clover EFI, and selected "boot with injected kexts" to boot.

**Comment by mn19941219** [comment]
Bluetooth is work fine, you just boot normally

**Comment by johnnync13** [comment]
repor to bluetooth GitHub https://github.com/zxystd/IntelBluetoothFirmware
