### ISSUE TITLE
Usb flash drive

### ISSUE THREAD

**Issue by rodion1322** [johnnync13/Xiaomi-Notebook-Air-1Gen#68]
Hi. On last opencore not seeing usb flash drive (usb work like iphone connect and usb wifi)

**Comment by johnnync13** [comment]
What do you want to say?

**Comment by rodion1322** [comment]
Sorry for bad english. I want say “usb disk“ not mount to mac, and i can’t see It with diskutil

**Comment by johnnync13** [comment]
I don't know. You change the USB port, usb disk ?

**Comment by rodion1322** [comment]
Today i want try another disk and i reply here. I only know it disk worked when we use Usbinject kext

**Comment by rodion1322** [comment]
Now on it disk installed loader OC, i can boot with it and oc see it, but mac nope

**Comment by Leigerr** [comment]
I had the same problem a few days ago, using opencore (EFIOC), without modifying any files in this folder, type-c Port Hub can only use USB 2.0. USB3.0 is only available when I replace /EFIOC/OC/Kexts/USBPorts.kext with /USB/All/USBPorts.kext, but this operation makes the computer unable to sleep and wake up normally. In addition, no matter which USBPorts.kext is used, the power light is on when the computer is turned off. Anyway, thank you for providing these codes.

**Comment by rodion1322** [comment]
Well i buy new usb dusk (usb 2.0) and it works. But old usb disk has usb 3.0 and not work(

**Comment by mn19941219** [comment]
> Well i buy new usb disk (usb 2.0) and it works. But old usb disk has usb 3.0 and not work(

USB3.0 word fine on right side USB Port
USB Type-C and left side USB Port only support USB2.0
