### ISSUE TITLE
Anyone know   how to  reset bios password?

### ISSUE THREAD

**Issue by rainplus** [johnnync13/Xiaomi-Notebook-Air-1Gen#69]
bios password forgot ,do you know any way to reset it ?（which i don't know version of bios）

and use the way as  below, but i can't see the efi in boot list.

### OpenCore method:
1. On your mac, create your macOS USB install media (e.g. https://support.apple.com/en-us/HT201372)
1. Mount the ESP (EFI System Partition) on your USB stick: (check that you mount the correct EFI partition, numbers will vary!!!)
diskutil list
sudo diskutil mount /dev/disk3s1
1. Copy and overwrite the contents of the EFI folder on your USB stick with the contents of the EFIOC (opencore) folder from this website.
1. Eject the USB stick from your computer and insert in the Xiaomi laptop.
1. Now boot the Xiaomi laptop from the install media (if trackpad is not working, use USB mouse. If network connection needed, use a Apple compatible USB Ethernet adapter)

it cloud started but had faild with the secureboot

**Comment by 977844579** [comment]
Need to replace BIOS chip

**Comment by rainplus** [comment]
> Need to replace BIOS chip

so sad for me. so it can't be install macos?

**Comment by 977844579** [comment]
修理它大约需要100元。 需要刷BIOS

**Comment by 977844579** [comment]
It costs about 100 yuan to repair it. Need to flash BIOS

**Comment by rainplus** [comment]
> It costs about 100 yuan to repair it. Need to flash BIOS

Where to go to do this, can only go to Xiaomi After-sales service center?

**Comment by rainplus** [comment]
update boot from clover success ,but faild with oc,but i like the oc way..

**Comment by 977844579** [comment]
https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen#bios-modification

**Comment by 977844579** [comment]
Maybe you need to read this
