### ISSUE TITLE
doesn't always go to sleep

### ISSUE THREAD

**Issue by Overmay** [johnnync13/Xiaomi-Notebook-Air-1Gen#70]
1) Doesn’t always go to sleep after closing the laptop cover. sometimes can't turn off.
2) if asleep, Usb does not wake up after sleep.

bootloader clover. 7.2.9

**Comment by Overmay** [comment]
sorry.  read the topic below.  But can I remove the Bluetooth.kext so that everything works?  I do not use it.

**Comment by johnnync13** [comment]
it is a bug from bluetooth kext

**Comment by clinging-al** [comment]
I also have the problem that the USB cannot wake up after the lid. Can I fix the lid hibernation problem by deleting the two kexts of Bluetooth?
