### ISSUE TITLE
bluetooth not work by boot from ssd!

### ISSUE THREAD

**Issue by rainplus** [johnnync13/Xiaomi-Notebook-Air-1Gen#71]
use clover boot.

i use usb stick boot  the bluetooth working, but not working boot from ssd.

i not copy the kexts of bluetooth into te /lib../ext...

**Comment by johnnync13** [comment]
I don't know what you want to say

**Comment by rainplus** [comment]
> I don't know what you want to say

Bluetooth cannot be used after installation

However, Bluetooth is effective during the  boot installation process(clover).
After entering macos from the computer disk, Bluetooth is not effective

**Comment by johnnync13** [comment]
Report to Bluetooth kext repository
