### ISSUE TITLE
Switch to OC failed, freezing in the white Apple logo

### ISSUE THREAD

**Issue by jimmymitlavigne** [johnnync13/Xiaomi-Notebook-Air-1Gen#75]
Trying to use OC
How to switch the EFI back?
Can’t open now. freezing in the white apple logo.
No progress bar

**Comment by johnnync13** [comment]
@jimmymitlavigne try the last release

**Comment by jimmymitlavigne** [comment]
Thanks for you reply. Actually I was use the last release. Now I can’t get in the system. How to switch the efi. I copy the all OC efi file. I don’t know why.

**Comment by wxyttty** [comment]
Click the space bar and select clean nvram

**Comment by jimmymitlavigne** [comment]
> Click the space bar and select clean nvram

Thanks for your reply. I try the clear nvram and reset nvram still not working. 
Still freezing in white apple logo

**Comment by wxyttty** [comment]
-v跑个码

**Comment by jimmymitlavigne** [comment]
> -v跑个码

谢谢回复。怎么-V  ，选项在哪

**Comment by wxyttty** [comment]
win+v

**Comment by jimmymitlavigne** [comment]
> win+v

按照错误代码折腾了一晚上。最后还是重装了。用clover就没什么问题。准备有时间再试一试OC
