### ISSUE TITLE
I found that when the logo progress bar is in the middle, it will start to restart.

### ISSUE THREAD

**Issue by 977844579** [johnnync13/Xiaomi-Notebook-Air-1Gen#76]
Hello sir, after testing the new version, I found that when the logo progress bar is in the middle, it will start to restart. Thank you for your answer.

**Comment by 977844579** [comment]
@johnnync13

**Comment by 977844579** [comment]
![66656A9A-F9E7-4195-BB9F-55E44BC9575D](https://user-images.githubusercontent.com/41711995/83697689-40905d80-a632-11ea-8c75-72d43154b89f.jpeg)

**Comment by wangyuchen123** [comment]
> Hello sir, after testing the new version, I found that when the logo progress bar is in the middle, it will start to restart. Thank you for your answer.

Me too

**Comment by johnnync13** [comment]
try new release

**Comment by wangyuchen123** [comment]
thanks a lot

**Comment by 977844579** [comment]
Sir, it's still looping and restarting. @johnnync13

**Comment by wangyuchen123** [comment]
7.3.3 still
