### ISSUE TITLE
Cannot install macOS

### ISSUE THREAD

**Issue by teci98** [johnnync13/Xiaomi-Notebook-Air-1Gen#77]
I tried everything but i can't install macos, always prompt a messagge that said "The recovery server could not be contacted"
![IMG20200605151101](https://user-images.githubusercontent.com/49975309/83880069-edf09780-a73e-11ea-9d69-e57cabcd50d2.jpg)
Can anyone help me?

**Comment by 977844579** [comment]
https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen#first-of-all-i-am-not-responsible-for-what-can-happen-to-your-laptop

**Comment by teci98** [comment]
> https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen#first-of-all-i-am-not-responsible-for-what-can-happen-to-your-laptop

I tried unlocking cfg lock and enabling SpeedShift but still have the same problem

**Comment by 977844579** [comment]
Has Bios been upgraded?

**Comment by teci98** [comment]
yes, when i write a command, it set the bios value

**Comment by 977844579** [comment]
You can try to install Catalina, efi choose 7.2.9

**Comment by 977844579** [comment]
You need to connect to the network and pay attention to whether the time is normal.

**Comment by johnnync13** [comment]
High Sierra is old for this efi, try catalina. And if you use gibmacos is necessary have internet

**Comment by teci98** [comment]
i tried to make the bootable USB with a macOS VM but the laptop didnt detect it
i also have a compatible ethernet adapter but it isn't detected either

**Comment by teci98** [comment]
Hi again, i'm trying to make the usb in macos but i can't create the EFI partition, so i can't boot in the laptop

**Comment by johnnync13** [comment]
you can create partition with clover installation pkg

**Comment by johnnync13** [comment]
https://youtu.be/FgJucJKbn2Y
