### ISSUE TITLE
我也不明白是什么原因，开机就这样了

### ISSUE THREAD

**Issue by boysuper** [johnnync13/Xiaomi-Notebook-Air-1Gen#79]
![IMG_20200607_222740](https://user-images.githubusercontent.com/32890519/83972768-a15eb500-a914-11ea-88ac-9806668a26d4.jpg)
![IMG_20200607_222715](https://user-images.githubusercontent.com/32890519/83972772-a7ed2c80-a914-11ea-8cf3-be54a29b1be2.jpg)
如图，用Clover启动，更新了v7.3.4就成了这样子，我使用的上一个版本是v0.6
（Error: already started returned from AptioMemoryFix.efi）

**Comment by boysuper** [comment]
主题文字乱码，图标丢失

**Comment by johnnync13** [comment]
I not support clover
