### ISSUE TITLE
No trackpad

### ISSUE THREAD

**Issue by finner** [johnnync13/Xiaomi-Notebook-Air-1Gen#8]
Installed 10.4.4 with your latest EFI. It boots but trackpad wont work at all. As I see you included once again voodooI2C which isnt needed since we dont have an I2C bus on our 2016 model but an SMBUS.
Also shutdown doesnt work anymore

**Comment by johnnync13** [comment]
On DSDT.aml appear i2c @finner

**Comment by johnnync13** [comment]
@finner try v3.0

**Comment by bianyingshan** [comment]
@johnnync13 Have you fixed the shutdown problem? Whether there are ideas, I have tried many ways, but ultimately did not repair the problem.

**Comment by johnnync13** [comment]
@bianyingshan I don't have this laptop, I have 12.5 m6y30. To fix correctly, you need usb drive 2.0, usb drive 3.0, type-c 3.0 and type-c 2.0 (for example like connect iphone typeC lightning) and with hackintool, you see when connect usb port, usb change to green. use this with all usb drive on all ports usb

**Comment by johnnync13** [comment]
@bianyingshan try my last efi repository

**Comment by finner** [comment]
Using latest v3 trackpad works although not as expected. Force click is enabled by default therefore I cannot use left click to open apps and under Trackpad it shows no trackpad installed

**Comment by shomerchang** [comment]
trackpad working perfect, amazing!Thx
but it can't drag file.
btw: under Trackpad it shows no trackpad installed.

**Comment by walking-hard** [comment]
Thanks for your sharing. I meet some issues:
1.TouchPad cant not work, even can't click. After I replac VoodoPS2Controller.kext with AppleSmartPS2Touchpad.kext, my touchpad can click(press, isn't touch). But befor I unlock computer I can click by touch.
2.Can not shutdown. When I click shutdown, the power key still keep light and CPU fan still work.

**Comment by johnnync13** [comment]
@walking-hard @shomerchang @finner @bianyingshan for fix trackpad I need that use this and send me files and fixes https://github.com/williambj1/GenI2C

**Comment by johnnync13** [comment]
I'm close to being able to patch the trackpad like a magictrackpad, nobody wants to be a tester?

**Comment by finner** [comment]
@johnnync13  I am offering to beta test.

**Comment by johnnync13** [comment]
@finner https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/v3.3.2

**Comment by shomerchang** [comment]
only https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/releases/tag/v3.0 trackpad can work, others(above v3.0) can not work at all. Is it because I use Mojave? 
BTW:My gaming laptop(installed Catalina) which use your latest EFI works very well(include trackpad),THX!

**Comment by johnnync13** [comment]
@shomerchang use the last. The problem is this laptop, I think that not have i2c trackpad...

**Comment by FallenChromium** [comment]
@johnnync13 Indeed I have a Xiaomi Mi Notebook Pro, and a friend of mine has Mi Notebook Air 12.5 with i5-6200U (thus I was lurking for a working repo). USB is a mess, leads to inability to shutdown and dead USB ports after sleep. Trackpad is 100% I2C-compatible because it has Precision Touchpad settings on Windows, which can be used by VoodooI2CHID, it's just not patched right. I will try to do something about it now and will ping back on results, now trying to get USB ports working normally.

**Comment by johnnync13** [comment]
@FallenChromium on windows, the trackpad is by SBUS and has synaptic driver and for example xiaomi notebook pro is tpd0 and is elan trackpad.

**Comment by FallenChromium** [comment]
You're right about Synaptics and SBUS, but it doesn't cancel that it can work in Precision mode (as I said, settings are in place), which means it's I2C and it's manageable through VoodooI2CHID. By the way, have you tried VoodooI2CSynaptics? Looks like a better option. If you need any help with this laptop, testing, files, dumps, you can ping me. Soon I'll travel a bit but in a week I will have full access to it

**Comment by johnnync13** [comment]
@FallenChromium this tool is automatic patch https://github.com/williambj1/GenI2C

**Comment by johnnync13** [comment]
trackpad is working now like magic trackpad
