### ISSUE TITLE
Typec/USB headphones make a harsh sound

### ISSUE THREAD

**Issue by clinging-al** [johnnync13/Xiaomi-Notebook-Air-1Gen#80]
First of all, thank you for your long-term update and maintenance. If you use a 3.5mm headset, everything is normal, but the typec/USB headset makes a harsh sound. This happens every time I adjust the volume, whether it is OpenCore or Clover. Now I use OpenCore. I use the Xiaomi Mi Noise Cancelling Headphone typec version

**Comment by johnnync13** [comment]
uoh is a new problem that never I have seen. if you can report to tonymacx86 --> hackintool or here https://github.com/acidanthera/bugtracker
