### ISSUE TITLE
Anyone test the wifi/AutoConnect command ? DId it work on OC?

### ISSUE THREAD

**Issue by jimmymitlavigne** [johnnync13/Xiaomi-Notebook-Air-1Gen#83]
Seeing their discussion, this one seems stable

**Comment by wxyttty** [comment]
前期应睡眠过久重启过3次，后来稳定不重启，2.4g有1/3速度，5g有1/2。不过有时明明连接成功可以浏览网页，但网易云音乐，App Store无法连接网络

**Comment by wxyttty** [comment]
不过我用的是6.7的kext

**Comment by johnnync13** [comment]
https://github.com/AppleIntelWifi/device-logs/issues/6#issuecomment-636360258
[Wi-Fi.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4779795/Wi-Fi.zip)
<img width="384" alt="Captura de pantalla 2020-06-15 a las 13 04 22" src="https://user-images.githubusercontent.com/22727137/84650533-bcc75280-af08-11ea-8451-e77c29482bab.png">

**Comment by jimmymitlavigne** [comment]
> [AppleIntelWifi/device-logs#6 (comment)](https://github.com/AppleIntelWifi/device-logs/issues/6#issuecomment-636360258)
> [Wi-Fi.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/4779795/Wi-Fi.zip)
> <img alt="Captura de pantalla 2020-06-15 a las 13 04 22" width="384" src="https://user-images.githubusercontent.com/22727137/84650533-bcc75280-af08-11ea-8451-e77c29482bab.png">

THanks! THis work perfect!

**Comment by jimmymitlavigne** [comment]
> 前期应睡眠过久重启过3次，后来稳定不重启，2.4g有1/3速度，5g有1/2。不过有时明明连接成功可以浏览网页，但网易云音乐，App Store无法连接网络

感谢回复! 这个autoconnect的我测试了下 也可以连接但是每次开机都要重新跑一次脚本,不是很方便 你可以试试Jonny发的这个  开机自动连接,跟原生体验差不多了
