### ISSUE TITLE
The USB and Bluetooth devices can not wake up

### ISSUE THREAD

**Issue by markshaw2008** [johnnync13/Xiaomi-Notebook-Air-1Gen#85]
TKS for all your works. I found an issue when I use the EFI with the OpenCore.

-----
When the laptop screen is closed, and I opened the laptop again , The USB and Bluetooth devices can not wake up and it just displayed as unavailable on the top menubar.

so could you please help how to fix the issue?

**Comment by ohhhr** [comment]
me too

**Comment by johnnync13** [comment]
Bluetooth kexts is the problem

**Comment by ohhhr** [comment]
usb doesnt wake up too
