### ISSUE TITLE
Can't Install macOS Big Sur

### ISSUE THREAD

**Issue by abmfy** [johnnync13/Xiaomi-Notebook-Air-1Gen#86]
When trying to install macOS Big Sur Beta, it paused at the white Apple logo and I had to restart. Maybe EFI is to be updated to support macOS Big Sur?

**Comment by abmfy** [comment]
Added "-v" boot arg and it seems that it stops here:
![IMG_1747](https://user-images.githubusercontent.com/20623941/85837216-596fd700-b7ca-11ea-805b-25376c584fdb.JPG)

**Comment by the-eric-kwok** [comment]
Be patient. Big Sur is too new for hackintosh community. There’s no way to direct install/upgrade to it.

**Comment by wxyttty** [comment]
想升级请用oc0.6工厂版，并编译最新kext，根据oc官方修改config.plist，29号oc大概率进不去，请用28号oc

**Comment by johnnync13** [comment]
hackintosh is not equal than have a macOS..
