### ISSUE TITLE
2560x1440 QHD HDMI resolution

### ISSUE THREAD

**Issue by j1exus** [johnnync13/Xiaomi-Notebook-Air-1Gen#87]
Hey!
Thanks for this awesome repo!

I can not setup 2560x1440 QHD for my external monitor. FullHD is max available resolution. 
Before I've tested Clover and everything seems to be ok. 
Do you have any ideas how to enable 2560x1440 for second screen?
Thanks!!

**Comment by johnnync13** [comment]
change some values with hackintool for igpu

**Comment by j1exus** [comment]
@johnnync13 Could you please give more info?
I'm new in hackintosh..
Thanks
