### ISSUE TITLE
usb cant wake up after sleep. is it solvable?

### ISSUE THREAD

**Issue by slotDumpling** [johnnync13/Xiaomi-Notebook-Air-1Gen#89]
if i close the lid putting the computer to sleep and then open it up, the usb wont work until i reboot it. i find a lot people have the same problem while others dont. did u find the same problem? is it solvable?

thank you for your hard work.

**Comment by sayed001** [comment]
I have the same issue on my laptop, mine is not xiaomi but this is an issue.

**Comment by sakoula** [comment]
@ohhhr check https://github.com/sakoula/XiaoMi-Air-6200U
