### ISSUE TITLE
ApleIntelSKLGraphicsFramebuffer

### ISSUE THREAD

**Issue by Nxys** [johnnync13/Xiaomi-Notebook-Air-1Gen#9]
Mojave 10.14.3(18D42)
Error：
<img width="807" alt="ApleIntelSKLGraphicsFramebuffer" src="https://user-images.githubusercontent.com/8848452/57195594-2eec0a80-6f87-11e9-97c8-fb32e46eb3cf.png">

**Comment by Nxys** [comment]
I just replaced the clover folder,need any other operations?

**Comment by johnnync13** [comment]
@Nxys try last version!
