### ISSUE TITLE
BIOS

### ISSUE THREAD

**Issue by can312** [johnnync13/Xiaomi-Notebook-Air-1Gen#91]

**Comment by can312** [comment]
![GitHub](https://user-images.githubusercontent.com/67582724/86526396-4a71de80-bec6-11ea-9465-c3b9fd1706c0.png)

**Comment by abmfy** [comment]
新的EFI好像已经不用修改BIOS了吧？我的就没更新到A09也可以引导

**Comment by can312** [comment]
我的bios没有更新A09，但是这个月四月份拿到售后修过，给我刷了A0B的，升级A09升级不了

**Comment by can312** [comment]
> 新的EFI好像已经不用修改BIOS了吧？我的就没更新到A09也可以引导

新的EFI确实是可以直接使用不用A09的
