### ISSUE TITLE
unable to adjust brightness of screen in win10 when booting from oc

### ISSUE THREAD

**Issue by BobbyJonas** [johnnync13/Xiaomi-Notebook-Air-1Gen#94]
if i boot win10 from oc with the given kexts, I couldn't adjust brightness via keyboard. Oppositely when bootin macOS, everything would be fine.

**Comment by shomerchang** [comment]
I've adjusted brightness key,
step1: remove ssdt-kbd.aml, ssdt-kdb0.aml from config.plist or disable them in the config.plist 
step2: add config_FN.plist's contents in my uploaded file into config.plist (ACPI->Patch)
step3: add ssdt-fn.aml into ACPI folder of your EFI
step4: reboot
[Fix Brightness.zip](https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/files/5026067/Fix.Brightness.zip)

**Comment by johnnync13** [comment]
so you can do pull request @shomerchang

**Comment by wxyttty** [comment]
I tried it,and it can turn up,but can't turn down

**Comment by shomerchang** [comment]
> I tried it,and it can turn up,but can't turn down

you'd better check your config.plist and  files in ACPI folder's  again. Follow the four steps.(https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/issues/94#issuecomment-668969823)

**It works well on my laptop.**  My OS version is BigSur beta6

**Comment by wxyttty** [comment]
I had checked it four times. OS also bigsur beta6

**Comment by shomerchang** [comment]
> so you can do pull request @shomerchang
I've forked from yours, and changed some places, removed many files.....
should I do pull request?
https://github.com/shomerchang/Xiaomi-Notebook-Air-1Gen

**Comment by shomerchang** [comment]
> I had checked it four times. OS also bigsur beta6

Try this. My EFI
https://github.com/shomerchang/Xiaomi-Notebook-Air-1Gen

**Comment by wxyttty** [comment]
I found the button was broken，it doesn't  work on mac and ctlos,too.It's been sent for repair

**Comment by johnnync13** [comment]
All fixes are here. https://github.com/daliansky/OC-little

**Comment by shomerchang** [comment]
> I found the button was broken，it doesn't work on mac and ctlos,too.It's been sent for repair

haha
