### ISSUE TITLE
Reboot when installing macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by abmfy** [johnnync13/Xiaomi-Notebook-Air-1Gen#96]
After installing OpenCore 6.0 released yesterday and some updated kexts, I can enter the installation UI of macOS Big Sur by OTA upgrade. However when I chose the language and clicked next, a window titled "macOS Update Assistant" appeared and caused a reboot. Anyone could help? Thanks a lot!
装完昨天发布的OpenCore 6.0和一些更新的kext之后能进OTA升级的macOS Big Sur安装界面了，但是选完语言点下一步之后弹出来一个叫“macOS更新助理”的窗口，接着就重启了。有没有大神帮帮忙，感激不尽！

**Comment by 977844579** [comment]
我升级成功了，没遇到你这个问题

**Comment by abmfy** [comment]
Upgrade succeeded after updated to Beta 3. I used Beta 1 and failed before.
用Beta 3就可以了，我之前用的Beta 1
