### ISSUE TITLE
Unable to boot using 7.4 or 7.4.1

### ISSUE THREAD

**Issue by finner** [johnnync13/Xiaomi-Notebook-Air-1Gen#99]
Until release 7.3.9 I could boot to Mojave just normally. After replacing the EFI with the latest one OC menh shows up, I choose OSX and then it loops back to the selection menu.

**Comment by johnnync13** [comment]
try v7.4.2

**Comment by johnnync13** [comment]
@finner

**Comment by finner** [comment]
Works fine now! Thanks
